### PR TITLE
feat(colors): add new blend function

### PR DESCRIPTION
**Pull request by hawkeye64**
as per: https://www.w3.org/TR/compositing-1/#simplealphacompositing

### CODE REVIEW

**Comment by hawkeye64** [comment]
Here is a codepen of the new method: https://codepen.io/Hawkeye64/pen/OJPEPBN

**Comment by jesusvilla** [comment]
You're amazing @hawkeye64

**Comment by rstoenescu** [comment]
Wonderful!

**Comment by rstoenescu** [comment]
Will go into v1.7.1.

**Pull request merged**
