### PR TITLE
QUploader add file sync

### PR DESCRIPTION
**Pull request by druppy**
This fix make sure the `add` event only gets called when all file info have been loaded, by making a promise per file that need info.

Sorry, should have made a issue first, crossing fingers :-)

/BL

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/master/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rstoenescu** [comment]
Also, please follow the already establish style (if's, parenthesis etc). Thanks for taking time for a PR!

**Comment by druppy** [comment]
It build and it lints, and it fall back to old behaviour if no files are detected, we will use it as soon as we have a beta build of 0.15 :-)

**Comment by rstoenescu** [comment]
Follow the instructions here: https://github.com/quasarframework/quasar-starter-kit so you can test it. Or test it directly on Quasar's repo (/dev folder).

**Comment by druppy** [comment]
Ok, tested this on dev repos (npm run dev), and it does indeed wait for the files to complete there loading before we call the emit.

Some have added strange timeouts in the add event handler to compensate, and this code will still work as expected, but the timeout will of course not be needed anymore :-)

**Pull request merged**
