### PR TITLE
emit click event on qFab

### PR DESCRIPTION
**Pull request by m0dch3n**
https://jsfiddle.net/xrdapu5t/ 

Currently qFab isn't emitting the click event, when clicked

### CODE REVIEW

**Comment by rstoenescu** [comment]
Hi,

Thank you for wanting to contribute!
This is unnecessary though. You are trying to catch the native DOM "click" event and you can do that by using the ".native" modifier:

```html
<q-fab @click.native="onClick" ....
```

https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components

**Comment by m0dch3n** [comment]
Hi,

ok, I agree, it's the same like .native, so this commit is useless...

However .native is also triggered, when clicking on an action button...

c.f. https://jsfiddle.net/fwjpbLuz/

PS: The documentation also says
```
#QFab Vue Events

@click | Triggered when clicking/tapping on main FAB after it was already opened.
```

This @click event isn't triggered at all...

**Comment by m0dch3n** [comment]
What do you think about this

```
  methods: {
    click (e) {
      e.stopPropagation();
      this.__qFabClose().then(() => {
        this.$emit('click', e)
      })
    }
  },
```

in QFabAction ?

**Comment by rstoenescu** [comment]
Fixed the documentation. QFab `@click` is obsolete (went away long ago).
Why stopPropagation? If you need to add it you can do it from the `@click="e => { e.stopPropagation(); doSomethingElse() }`

**Comment by m0dch3n** [comment]
.native on QFab is also triggered, if you click on QFabAction.

So if you only want to know if the main fab button was clicked, you need to stopPropagation or to check the origin in your event method

**Pull request closed without merging**
