### PR TITLE
feat: Inline Color Picker

### PR DESCRIPTION
**Pull request by altitudems**
This adds a simple Inline Color Picker Component. I imagine we will want to treat this similar to how the DateTime component is treated. I am open to any suggestions for improvement.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe:
Requires the tinycolor2 package

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] It's been tested with all Quasar themes
- [x] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/master/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
screen shot 2017-09-05 at 11 25 00 am

### CODE REVIEW

**Comment by altitudems** [comment]
If you get some time, let me know if you need anything changed for this to get accepted. Once I know the direction you want to take this I can implement it better with forms, etc. and write some docs. If we want to wait until there is a clearer path for community components, that is understandable.

**Comment by rstoenescu** [comment]
This is such a great PR!! Will be part of v0.15. Please allow me some time before I merge it.

**Comment by rstoenescu** [comment]
Can we avoid the additional dependency?

**Comment by altitudems** [comment]
I'm sure we could, we would have to reimplement some of the math from tinycolor2.

How important is it to spit out color in the different formats? Is Hex + RGBA enough? Or do we need HSV, etc.?

**Comment by altitudems** [comment]
I went ahead and removed tinycolor2, I had to add two color functions. I dropped HSL and the value/model is now a flat object: { h: 0, s: 0, v: 0, r: 0, g: 0, b: 0, a: 1, hex: '#000000' }

**Comment by spectrolite** [comment]
Great job there.
But it’s really too bad you dropped HSL, which is probably the most intuitive colourspace for endusers.
If you need help with the math to put it back in, feel free to pm me on the forum.

**Comment by altitudems** [comment]
@spectrolite Thanks for the feedback. I'm not sure how I feel about adding both HSL and HSV/B. I would rather choose one or the other and keep the value object flat for simplicity.

Some things to consider:

- HSB/HSV values cannot be present along with HSL values (H and S are not in common)
- The UI only shows RGBA and Hex values to the user, so user intuitiveness is not a factor
- If you need HSL values somewhere in your app you could still do a quick conversion yourself
- The math is not hard at all, and I can borrow that from somewhere else

Personally I don't care if we drop HSV for HSL or drop both. I think providing at least RGBA and Hex is enough.

**Pull request merged**
