### PR TITLE
docs(app-vite): improve supporting TS guide

### PR DESCRIPTION
**Pull request by ShlomoCode**
When trying to access a variable from the env file, like this:
`import.meta.env.VITE_YOUR_KEY`
getting a typescript error:
`Property 'env' does not exist on type 'ImportMeta'`
(the variable does not exist under process.env.VITE_YOUR_KEY)

This was solved ([officially](https://vitejs.dev/guide/features.html#client-types)) by adding the vite client tapes.
I suggest adding this by default, to save users this friction (like SvelteKit, see https://github.com/vitejs/vite/issues/9539#issuecomment-1609590074)

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [ ] Feature
- [x] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on an Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by ShlomoCode** [comment]
I will create this as an issue

**Comment by yusufkandemir** [comment]
Doing that makes the user have to manually include every single `@types/*` package they install, see [TS docs](https://www.typescriptlang.org/tsconfig#types). A better solution is adding the snippet below to a `.d.ts` file that is included in the project.
```ts
/// <reference types="vite/client" /> 
```
This is scaffolded by create-quasar:
https://github.com/quasarframework/quasar/blob/f851b491a02583402a7a7c40818ac80b09192f4e/create-quasar/templates/app/quasar-v2/ts-vite/BASE/src/shims-vue.d.ts#L3

So, please take a different approach. Instead of adding it to `tsconfig.json`, add the `src/*.d.ts` to the related docs page. Only the `/// <reference types="vite/client" />` would cover your original intention, but the documentation should have the rest of the files for full coverage. Thanks for your efforts.

**Comment by ShlomoCode** [comment]
The scaffolding file covers a new project, but does not cover my case, that I initially wrote the project in js, then decided to switch to ts, and followed the [quasar guide](https://quasar.dev/quasar-cli-vite/supporting-ts/):
>The Typescript support is not added by default to your project (unless you selected TS when you created your project folder), but it can be easily integrated by following the guide on this page.

If so, the guide should cover as smooth a migration as possible...
Maybe instead of what I changed, I should add an information box that in order to solve the error in accessing import.env the reference line must be added?

> add the `src/*.d.ts` to the related docs page

Sorry, I didn't understand what you mean. Could you elaborate?

**Comment by yusufkandemir** [comment]
> The scaffolding file covers a new project, but does not cover my case, that I initially wrote the project in js, then decided to switch to ts

Exactly, that's why I think the guide should cover as much as possible by providing up-to-date information compared to what's being scaffolded currently.

> add the src/*.d.ts to the related docs page

this means, instead of the `tsconfig.json` change, update the docs page to mention the `src*.d.ts` files, e.g.:
> create `src/shims-vue.d.ts` with the following contents:
> ... (insert the contents from https://github.com/quasarframework/quasar/blob/dev/create-quasar/templates/app/quasar-v2/ts-vite/BASE/src/shims-vue.d.ts to here)
> create `src/quasar.d.ts` with the following contents:
> ... insert https://github.com/quasarframework/quasar/blob/dev/create-quasar/templates/app/quasar-v2/ts-vite/BASE/src/quasar.d.ts
> create `src/env.d.ts` with the following contents:
> ... insert https://github.com/quasarframework/quasar/blob/dev/create-quasar/templates/app/quasar-v2/ts-vite/BASE/src/env.d.ts

**Comment by ShlomoCode** [comment]
It should also be added that if you use bex mode, the `@types/chrome` package must also be installed?
and add these lines to `background.ts` file:
https://github.com/ShlomoCode/quasar/blob/48d092ed69ce03268d30eec27ef7b9ebf584fc00/app-vite/templates/bex/ts/manifest-v2/background.ts#L16-L27

**Comment by yusufkandemir** [comment]
`@types/chrome` is shipped from app-vite/app-webpack(_as it's in `dependencies`_), it's not installed separately, so it should work as is. As for the code spinnet, yes, please add it.

**Comment by ShlomoCode** [comment]
@yusufkandemir can you take a look?

**Comment by yusufkandemir** [comment]
Thanks for contributing 👏 I have made some improvements to your content and added Pinia, Vuex, PWA, and Electron sections, thanks to the structure you've created.

**Comment by ShlomoCode** [comment]
I notice now that the [linting support instructions](https://quasar.dev/quasar-cli-vite/supporting-ts#linting-setup) are only suitable for the case of designing using prettieer and not eslint `standard`/`Airbnb`
How is it right to do it? You actually need a nested tabs - which packages to install, and with which package manager

**Pull request merged**
