### PR TITLE
feat (Double Range): Drag by range, disable min/max.

### PR DESCRIPTION
**Pull request by CookieJon**
**feat (Double Range): Drag by range, disable min/max.**

Add props to double-range to enable dragging by the entire range, and disabling
dragging by min and/or max handles.

Issue #14 Range - drag whole range enhancement feature request proposal

### CODE REVIEW

**Comment by rstoenescu** [comment]
Great great work!
Did an initial testing and it works good. Please allow me some time until merging this in. I constantly get hijacked by other issues and I want to make a final thorough testing before the merge.

Thank you so much for your efforts!

**Comment by CookieJon** [comment]
Phew!  I was a bit worried my sad old coding style wouldn't be up to scratch lol. 
No urgency with the merge.
FYI: I've only tested it on **Windows Desktop+Chrome** (I don't actually own a smartphone, yes, yes I know...)

**Comment by smolinari** [comment]
>(I don't actually own a smartphone, yes, yes I know...)

Get out of here? Really? :smile: 

Scott

**Comment by rstoenescu** [comment]
Merged. Such good work!

**Pull request merged**
