### PR TITLE
fix(app-vite): Fix BEX feature flag

### PR DESCRIPTION
**Pull request by yusufkandemir**
**What kind of change does this PR introduce?**

- Bugfix

**Does this PR introduce a breaking change?**

- No

**The PR fulfills these requirements:**

- It's submitted to the `dev` branch (or `v[X]` branch)

**Other information:**
Reported by NeoScaler#0531 on [our Discord Server](https://chat.quasar.dev).

### CODE REVIEW

**Comment by neoscaler** [comment]
For me this still does not work after updating to app-vite-1.0.0. Do I have to configure something too see the bex object?

**Comment by yusufkandemir** [comment]
@neoscaler this change affects the file template, so it will become effective on file generation. You can remove `bex-flag.d.ts` in your project, then run the dev server or build in BEX mode to trigger file generation.

**Comment by neoscaler** [comment]
> @neoscaler this change affects the file template, so it will become effective on file generation. You can remove `bex-flag.d.ts` in your project, then run the dev server or build in BEX mode to trigger file generation.

Thanks for your help and suggestions. Unfortunately this does not do the trick. The file looks good, but still I can't use `$q.bex`, stating that bex is not available in QVueGlobals.

@yusufkandemir any ideas?

**Comment by yusufkandemir** [comment]
@neoscaler I can't reproduce the problem. Share a repro(_URL of a GitHub repo_) and the output of `quasar info`.

**Comment by neoscaler** [comment]
> @neoscaler I can't reproduce the problem. Share a repro(_URL of a GitHub repo_) and the output of `quasar info`.

@yusufkandemir You can see the problem in https://github.com/neoscaler/gittab/tree/feature/gitlab-pr-support.

Output of quasar info is:

`
Operating System - Linux(5.15.0-30-generic) - linux/x64
NodeJs - 16.13.2

Global packages
  NPM - 8.5.5
  yarn - 1.22.18
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.7.1 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.0.1 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.14.0 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.36 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.15
  pinia - 2.0.14 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.1 -- Native-ESM powered web dev build tool
  eslint - 8.16.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - zbook-g4
`

**Comment by yusufkandemir** [comment]
@neoscaler you have this in your `tsconfig.json`:
```json
"include": [
  "src/**/*.ts",
  "src/**/*.d.ts",
  "src/**/*.tsx",
  "src/**/*.vue"
]
```
So, `src-bex/bex-flag.d.ts` is not included, causing `$q.bex` to be undefined. This config might be leftover from old versions of the app template, so you need to update it. It will work if you change it to the following:
```json
"include": [
  "src*/**/*.ts",
  "src*/**/*.d.ts",
  "src*/**/*.tsx",
  "src*/**/*.vue"
]
```

**Comment by neoscaler** [comment]
Thanks a lot! Indeed this has to be a leftover of generating the app with the previous beta version, as I never touched this configuration.

**Pull request merged**
