### PR TITLE
fix(lang): Correct date picker header date format for french #7991

### PR DESCRIPTION
**Pull request by webnoob**

### CODE REVIEW

**Comment by webnoob** [comment]
Sorry for the messy history. My tree went crazy...

**Comment by IlCallo** [comment]
Maybe better to redo the branch starting from up-to-date dev branch? So we avoid the commit frenzy :P

**Comment by hawkeye64** [comment]
I always do a branch off the upstream branch to avoid the merge messages

**Comment by webnoob** [comment]
Doesn't matter, they get squashed. I branched the way I normally do but something odd happened, not sure why. Either way, it won't matter in the main commit to Quasar as the squash will sort it.

**Pull request merged**
