### PR TITLE
Add guarani language to i18n

### PR DESCRIPTION
**Pull request by damvaz**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**
A new translation file for guarani language. Necessary for Paraguay, Brasil, Argentina, Bolivia and other countries.

### CODE REVIEW

**Comment by rstoenescu** [comment]
Hi,

Thanks for submitting a language pack!

Isn't Guarani ISO code "gn" instead of "gu"? https://en.wikipedia.org/wiki/ISO_639-3
Seems like "gu" is for Gujarati?

**Comment by damvaz** [comment]
Its "gn"

**Comment by damvaz** [comment]
I must change the filename right?

**Comment by rstoenescu** [comment]
Yep. Thank you!

**Comment by rstoenescu** [comment]
Will be available in next Quasar version. Thanks.

**Comment by damvaz** [comment]
Thank you for create an awesome framework!

**Pull request merged**
