### PR TITLE
Fix lang switch description to working example

### PR DESCRIPTION
**Pull request by Serhioromano**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [x] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rstoenescu** [comment]
Hi,

I'm so sorry, but it's the same thing as in the other PR. You've edited the Quasar Language pack page instead of possibly https://quasar.dev/options/app-internationalization

**Comment by Serhioromano** [comment]
It s not the same. I separated it into 2 Prs on purpose. One PR adds new title how to add language and this is not described anywhere on your docs and other fixes example on how to switch languages because the one you had did not work and it took me one day to figure out what is wrong with that example. Also, that example have nothing to do with the app language but with Quasar languages. 

It is so sad to see that both my Prs was rejected. It did not matter of opinion it was directions that work.

**Comment by rstoenescu** [comment]
It mixes App Internationalization with Quasar Language packs... Please update accordingly so I can merge.

**Comment by Serhioromano** [comment]
Close it, I'll create new PR.

**Pull request closed without merging**
