### PR TITLE
Firebase Storage support for q-uploader

### PR DESCRIPTION
**Pull request by valeriancure**
**What kind of change does this PR introduce?** (check at least one)

- [x] Feature

**Does this PR introduce a breaking change?** (check one)

- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs] -> **soon**

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

# Major feature : Q-Uploader now 100% supports uploading to Firebase Storage.
Just provide a `Firebase Storage Ref` instead of an url, and you're good.
All existing features are preserved : progress, events, abort, multiple files, additional fields ...

New prop : `firebaseStorage` (Object || Function)

## Simplest Usage
If prop `firebaseStorage` is a Firebase Storage Ref :
```
  const storageRef = firebase.storage().ref('quasar-uploader-test')
  ...
  <q-uploader :firebase-storage="storageRef" ... />
```
When you do **not** provide an `url` prop, q-uploader will look at the firebaseStorage prop and use it.
Everything else is taken care of.
As a bonus, the original `additionalFields` prop is preserved, and used to populate the `metadata.customData` that will be saved with your file.

## Avdanced Usage
If prop `firebaseStorage` is a function that returns a Firebase Storage Ref :
```
  makeUploadTaskWithTimestamp (file) {
      const originalName = file.name
      const newFilename = `${Date.now()}.${file.name}`
      const metadata = {
        customMetadata: {
          originalName
        }
      }
      return storageRef.child(newFilename).put(file, metadata)
    }
  ...
  <q-uploader :firebase-storage="makeUploadTaskWithTimestamp " ... />
```
If `firebaseStorage` is a function, it will be passed a `file` object, and should return a Firebase Upload Task.
This is very useful if, by example, you wish to rename a file before upload : you can avoid overwriting an existing file with the same name.

You can also use this function to populate the metadata.customData object, to save any useful data with your file.

# Minor feature : filter files before they reach the queue

New prop : `fileFilter` (Function)

Works with both the original `url` mode, and `Firebase` mode.

```
<q-uploader :file-filter="file => /.+\.png$/i.exec(file.name)" ... />
```

Useful if you want to limit uploads to some file extension, or limit them by size, etc.
Doesn't replace a server-side check, but can avoid useless upload time/bandwidth waste (and user frustration).

Will emit a `filtered` event with the files that didn't pass the test : can be used to notify the user and explain him the reasons.

# Minor bonus (for the `dev` testing page) : usable default url
https://www.posttestserver.com/ as default url, I found it perfect for quick-testing the `url` mode, without having to set up my own test server.

***
# Test/Demo
in quasar folder :
`npm install firebase`
in /dev/data :
`copy firebase-storage-example.json as firebase-storage.json and fill it with your Firebase credentials`

then `quasar dev` and go to http://localhost:8080/#/components/uploader

Cheers 👍

### CODE REVIEW

**Comment by fchabouis** [comment]
Any idea if this is coming soon ?
Thanks !

**Comment by nothingismagick** [comment]
@valeriancure - There are only two conflicts here, would you mind resolving them?

**Comment by thugic** [comment]
Any news on this?

**Comment by valeriancure** [comment]
Hi, allow me a day or two, I'm working on a deep refactoring (have spent the whole day on it and it's almost finished)

Adding a `firebase-storage` prop was convenient, but what if we want to add another service provider tomorrow ; ending up with one prop per service would be a mess.

I'm working on a more flexible uploader. With ability for us to 'plug' hooks at some steps for more customization of the behavior.
I'll provide a firebase-storage helper that plugs in these hooks.

I try as much as possible to keep compatibility with the older version (for people using `url` and `urlFactory`)

**Review by oreing — APPROVED** [review]

**Comment by razbakov** [comment]
Any updates on this? Do you need help?

**Comment by nothingismagick** [comment]
Wow’ it’s been a long time.

I think the resolution would be in the implementation of the app extension.

https://github.com/quasarframework/app-extension-firebase

**Comment by razbakov** [comment]
So then maybe make sense to close this issue?

**Comment by rlynjb** [comment]
cant seem to make this work. i get 404 Not Found.. it seems to post on my local host rather than the storage.ref() i provided..

i provided firebase.storage().ref().child('webpics/')

is this correct?

**Comment by razbakov** [comment]
here is how I did it: https://gist.github.com/razbakov/378caedba3f24e3d8336442182528719

**Comment by nothingismagick** [comment]
@adamkpurdy - is this still helpful or is it something to close? Its pretty stale and doesn't comply with uploader anymore...

**Comment by tohagan** [comment]
Linking to https://github.com/quasarframework/app-extension-firebase/issues/1

**Comment by webnoob** [comment]
Closing as very outdated now and the aforementioned App Extension deals with Firebase.

**Pull request closed without merging**
