### PR TITLE
Add basque locale

### PR DESCRIPTION
**Pull request by ikerib**
**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [X] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [X] No

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch (or `v[X]` branch)
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**
Basque language

### CODE REVIEW

**Review by rstoenescu — CHANGES_REQUESTED** [review]
Hi @ikerib 

Getting a bit confused about this PR. If adding a language pack, then why also changing es.js with basque?

**Comment by ikerib** [comment]
oh! I used the spanish version to translate to basque but I made a mistake selecting the file. Sorry!
Close this PR and I'll create new one later

**Review by rstoenescu — CHANGES_REQUESTED** [review]
Thanks for replying quickly.

There's one more problem now - that this PR removes the es.js file :) Just add it back as it was.
Also, can you change the `isoName` and `nativaName` to the appropriate values? ('eu' - Euskara --- just taking a guess, but you know better)

```
isoName: 'es',
nativeName: 'Español',
```

**Comment by ikerib** [comment]
Done. Sorry for the inconveniences

**Comment by rstoenescu** [comment]
No worries.
Thank you for contributing!

This will go into Quasar v2.6.0 this week.

**Pull request merged**
