### PR TITLE
Clarification on setLocale vs getLocale

### LINKED ISSUE #4340: [v1] `this.$q.lang.getLocale()` is misleading
I've been using `setLocale()` to set the language the user has selected in my app but when checking this against `getLocale()` it doesn't match. I understand this is because `getLocale()` always returns the users locale (based on browser) but the name is misleading.

I propose it gets changed to `getBrowserLocale()` or `getUserLocale()`.

I'm aware I can get the information I need from `$q.lang` - this issue is merely to clear up confusion.

### PR DESCRIPTION
**Pull request by webnoob**
Fixes #4340

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rstoenescu** [comment]
There's no 'setLocale' for Quasar language packs

**Comment by webnoob** [comment]
Oops sorry, I meant `this.$q.lang.set()`. I will adjust.

**Comment by rstoenescu** [comment]
Thx for taking time for this!

**Comment by webnoob** [comment]
My pleasure. Will take more care over the information next time!

**Pull request merged**
