### PR TITLE
QLIST -  Add Inverted prop on Letter left/right-sides

### PR DESCRIPTION
**Pull request by sebastienroul**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/master/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by sebastienroul** [comment]
Arg, sorry, there's commit 21bb586 in the PR... sorry for this, I wanted too commit it independantly...
As soon as PR OK for you, I'll update the documentation...

**Comment by rstoenescu** [comment]
Hi,

This was implemented slightly different. It will be in future v0.15.
Thanks for creating this, though!

**Comment by sebastienroul** [comment]
@rstoenescu : OK no problem. Did you merge the https://github.com/quasarframework/quasar/commit/21bb586ac5eb8f1f45de4dd6e7378032f1b34239
It was in the PR ( but not about the subject...)

**Comment by rstoenescu** [comment]
No, that was not part of it. Would you be so kind to make a separate PR with that pls? Thx!

**Comment by sebastienroul** [comment]
@rstoenescu : Soory, it was previously in a PR, you already merge weeks ago... Thx

**Pull request closed without merging**
