### PR TITLE
docs: add survery results link

### PR DESCRIPTION
**Pull request by IlCallo**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [x] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rstoenescu** [comment]
Please port the updated version to vue3-work too.

**Comment by IlCallo** [comment]
Why removing the button on the docs tho? :thinking: 
Also, wanted to wait until tomorrow to merge, as I'll load the updated survey results slides this evening

**Comment by rstoenescu** [comment]
Doesn't looks good design-wise unfortunately

**Comment by IlCallo** [comment]
Can you add it in some way you think feels good? I'd say docs are much more visited than landing page

**Comment by rstoenescu** [comment]
Removed it on landing page, not docs. That's where the design is not ideal along with the v2 link. But unfortunately don't have time to design it better. We'll probably go with link on docs only at first.

**Comment by IlCallo** [comment]
Sorry, my bad, keep confusing the two files

**Pull request merged**
