### PR TITLE
[docs] suggest localhost.run instead of Serveo, fixes #6059

### LINKED ISSUE #6059: [docs] Serveo is down, provide localhost.run as alternative
https://quasar.dev/quasar-cli/opening-dev-server-to-public

Serveo is down because too many people used it to perform phishing attacks or spamming.
I found a new service (https://localhost.run/) which does the same thing, I don't know if it has downsides.

### PR DESCRIPTION
**Pull request by IlCallo**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [x] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [x] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
Closes #6059

### CODE REVIEW

**Comment by rstoenescu** [comment]
Thanks!

**Comment by ssuess** [comment]
To be honest, Serveo was better, because it allows you to request and use the same subdomain, obviating the need to keep giving users a new address every time (unless you want to)

**Comment by IlCallo** [comment]
Please read the related issue: serveo is offline, that's why we changed it

**Comment by ssuess** [comment]
I didn't realize, thanks for the update.

**Pull request merged**
