### PR TITLE
fix(vite-plugin): Properly fix auto-loading on prod (TS)

### PR DESCRIPTION
**Pull request by vincentauger**
**What kind of change does this PR introduce?** 

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on an Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**
`query['lang.ts']` will always return falsy as it will be an empty string when we want it "true". Just a small change required to make it work on line 36 of `query.js`:  `(query.type === 'script' && query['lang.ts'] !== void 0),`

Output below is with above suggestion and additional log output for context:
```ts
id: Organization.ts
query[lang.ts]: undefined / !!query[lang.ts]: false
query[lang.ts] !== void 0: false
query: {}
vue:false
template:false
script:true
style:false
id: /CreateOrganizationDialog.vue?vue&type=script&setup=true&lang.ts
query[lang.ts]: '' / !!query[lang.ts]: false 
query[lang.ts] !== void 0: true
query: { vue: '', type: 'script', setup: 'true', 'lang.ts': '' }
vue:true
template:true
script:true
style:false
```

### CODE REVIEW

**Comment by yusufkandemir** [comment]
I tried to fix this problem in https://github.com/quasarframework/quasar/commit/59ad455e002b14401d370f4ccd4ef1d435ff1b16 but didn't get the conditional part right. This PR solves that.

**Review by yusufkandemir — APPROVED** [review]

**Comment by yusufkandemir** [comment]
Thanks for contributing this fix and previously reporting the main issue in detail 👏

**Comment by vincentauger** [comment]
Thank you, you guys really are amazing. 🚀 Quasar is simply a pleasure to use. Happy I'm able to help a little. :)

**Comment by rstoenescu** [comment]
And released `@quasar/vite-plugin` v1.2.3 which has this fix.

**Comment by vincentauger** [comment]
Thanks! v1.2.3 tested successfully with my project.

**Pull request merged**
