### PR TITLE
fix: #3999 bug in infinite scroll behaviour

### LINKED ISSUE #3999: [V1] improve animation on infinite QCarousel
### JsFiddle
https://codepen.io/modchen/pen/LvwqMJ

### What steps did you take, to get the error?

Just swiping always to the next slide...

### What were you expecting?

When swiping "next" on the last slide (3), the transition get inverted to "prev", so it "jumps" back to (1) instead of continuing the transition to next slide. 

This breaks the infinite feeling, and it looks like, 1 is not next to 3 but before...

https://github.com/quasarframework/quasar/blob/a762d771505bdd99b0f014fdb491088cfad736f4/quasar/src/mixins/panel.js#L67

This line of code needs to take care of the "infinite" option

### PR DESCRIPTION
**Pull request by m0dch3n**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/dev/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

More information about the problem can be found in 

https://github.com/quasarframework/quasar/issues/3999

### CODE REVIEW

**Comment by rstoenescu** [comment]
Hi,

Thank you for contributing.
There are some serious performance problems with this approach:

* You do not guard oldVal with __isValidPanel (it might be not!)
* You call multiple times `this.__getPanelIndex(oldVal)` and `this.__getAvailablePanels()`. You could have stored the result in a variable rather than executing them multiple times.
* You always determine oldWasLastPane, newIsFirstPanel, newIsLastPanel even though there are cases where you might not need them.
* But the biggest problem is that calling this.__getAvailablePanels() is costly and breaks down performance.

Sorry, but will close this PR as a solution needs another approach.

**Comment by m0dch3n** [comment]
@rstoenescu 

Can you check, if this satisfying you, before I do a PR ?

https://github.com/quasarframework/quasar/compare/dev...m0dch3n:dev

- oldVal is now guarded
- vars, instead of multiple calls
- I only determine everything now in `this.infinite && validNewPanel && validOldPanel && index > -1 && oldIndex > -1`
- `this.__getAvailablePanels()` does not cost more then `this.__getPanelIndex`

PS: If this is still not ok, I think and it's better that someone else, is correcting https://github.com/quasarframework/quasar/issues/3999 because, as I already mentioned there, I don't know the quasar framework enough to fix the issue by myself...

**Comment by m0dch3n** [comment]
BTW

is there a reason, why the transition direction needs to be determined in the `watch` of `value` ? 

I'm asking this, because my solution only works for 3 or more panels. If you have only 2 panels in total,  in the infinite mode, you can't determine the direction only by the indexes...

You can get from panel 1 to 2, by swiping left **AND** right

So maybe panel.js should be refactored completly to not determine the transition by indexes, but at a point, where we still have the direction information....

How about simply puting the transition direction in the __go method, like here ?

https://github.com/quasarframework/quasar/compare/dev...m0dch3n:transitionTest

**Comment by m0dch3n** [comment]
I did some more commits on the refactoring approach branch, I think that's now, the best I can do in

https://github.com/quasarframework/quasar/compare/dev...m0dch3n:transitionTest

**Pull request closed without merging**
