### PR TITLE
fix(ae): fix file resolution for AEs with mixed dist folders

### PR DESCRIPTION
**Pull request by IlCallo**
**What kind of change does this PR introduce?** 

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**
#9758 assumed that a TS-using AE would have all its files into a dist folder referenced into the package.json, but this is not the case for existing AEs which already return a compiled dist (eg. testing AEs), which still have Quasar-specific scripts into `src` folder.

This is especially tricky since a common file name for dist entrypoints is `index`, which is the same used by Quasar for it's index script file. This tricked Quasar to execute the wrong `index.js` file.

This PR reverse the assumption to make the change opt-in: a file is first searched into the default location, and searched into the dist folder only if not found into the default location

### CODE REVIEW

**Comment by IlCallo** [comment]
@stefanvanherwijnen can you test this change with your setup? I want to merge it asap as it's blocking users to install testing AEs (and possibly other AEs) on new projects

**Comment by rstoenescu** [comment]
Do not merge this. Also, please do test PRs before merging.

**Comment by rstoenescu** [comment]
The support for TS should be accompanied by a PR to quasar-starter-kit-ui and quasar-starter-kit-app-extension repos too. And then a docs mention. Otherwise it's completely hidden for our devs.

**Comment by stefanvanherwijnen** [comment]
I thought both starter kits had the same package.json but this isn't the case:
https://github.com/quasarframework/quasar-starter-kit-app-extension/blob/master/package.json
https://github.com/quasarframework/quasar-starter-kit-ui/blob/master/template/app-extension/package.json

So my getPkgSrc function indeed does not work with the app-extension kit which I didn't realize...

@rstoenescu Before updating the starter kits some things (such as this issue) should be cleared up and fixed first. Right now it is hardcoded that the 'compiled' files are inside `src`, which is not the case for a TS project. Another major issue is the `render()` function which cannot easily support both rendering of JS and TS files without keeping equal copies of both.

@IlCallo 
For now you can just revert to the old behavior of hardcoded `src`. It is confusing but it works fine when tsc outputs to `src`.

**Comment by rstoenescu** [comment]
I've reverted and pushed a version which first looks into /dist/ then in /src. Released q/app v3.2.8 with it.
The package.json is identical. You're looking at the wrong one for app-extension starter kit. https://github.com/quasarframework/quasar-starter-kit-app-extension/blob/master/template/package.json

I understand the reasoning for these changes when it comes to adding support for TS, but a master plan needs to be developed first. My main issue here is that this got merged without being tested and it broke people's AEs, forcing me to do an urgent release with a fix, which is not ok.

Regardless, like I mentioned, the master plan needs to first be developed. From top to bottom, how will this work. There's indeed the `render()` method and possibly other that need a way to be solved. Then we'll have a green light for anyone to implement.

**Comment by IlCallo** [comment]
My fault about merging, I focused mostly on the types fixes when testing the PR (and wrongly didn't check them into the code after the last revision) and didn't spot the problem it would cause to some AEs

Gonna be more cautious next time

**Comment by stefanvanherwijnen** [comment]
I'll also properly test things first next time.

@rstoenescu You're right about the master plan and I opened an issue for it a while ago:  https://github.com/quasarframework/quasar/issues/7329

Personally I came to the conclusion that proper TS support is likely not possible with the current build tools and I ended up switching to Vite. With this PR users should be able to create their own TS project setup and if anyone figures out a proper way to solve all problems it would be great if they would comment on that issue.

Apologies for breaking things 😅

**Pull request closed without merging**
