### PR TITLE
add warning and warning label props to q-field

### PR DESCRIPTION
**Pull request by ghost**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/master/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rstoenescu** [comment]
Nice. Merged it. Thanks for taking time for a PR! Will be available in future v0.15.

**Comment by rstoenescu** [comment]
@nueko Would you also be so kind to add this to docs too?

**Comment by nueko** [comment]
the docs is here [@quasarframework/quasar-framework.org#dev](https://github.com/quasarframework/quasar-framework.org/tree/dev), right?

**Comment by rstoenescu** [comment]
Yep. If you are changing only one page you can hit the pencil at top right of page OR the edit link at the bottom of page. Make changes then hit create PR. Thank you so much!

**Pull request merged**
