### PR TITLE
feat(ui): All components to use SASS variable for font size #17264

### LINKED ISSUE #17264: All components to use SASS variable for font size
### Discussed in https://github.com/quasarframework/quasar/discussions/17263

<div type='discussions-op-text'>

<sup>Originally posted by **mstroeve** June  6, 2024</sup>
For our projects, we would like the font-sizes of the Quasar components to be adjustable to comply with WCAG accessibility standards and fit our design.
There are some font-sizes which have SASS variable overrides, but not all.

For example, the font-size of the .q-table th is hardcoded (12px) and the .q-table tbody td is hardcoded (13px).
We'd like to see all the hardcoded font-size variables inside the components (quasar/src/components) customizable in quasar/src/css/variables.sass

A component where it's already possible to alter it with a variable is i.e. the $button-font-size inside QBtn.sass.

Perhaps this involves more than only changing the font-size, since sometimes component heights and line-heights have the same hardcoded value as the font-size.
I.e. inside QBadge.sass there is a min-height and line-height defined with the same value as the font-size, where if we'd change the font-size only, things wouldn't fit properly anymore.

Line-height should also be adjustable there (and in other components), for WCAG AA compliance demands a minimum of 1.5, and that combined should make the min-height a value of (font-size * line-height) as default, which in the current situation would be the same if line-height has default value of 1, which is the same as the current pixel value of 12.

Anyway, with flexibility of variables, it can stay all the same by default but we'd be able to customize it for ourselves. </div>

### PR DESCRIPTION
**Pull request by ekamphuis82**
Resolves #17264

**What kind of change does this PR introduce?** 

- [x] Feature

**Does this PR introduce a breaking change?** 

- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on an Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by mstroeve** [comment]
@yusufkandemir as this is our first PR in this project can you give us feedback regarding the correct usage of guide lines in this PR?

**Comment by yusufkandemir** [comment]
@mstroeve with a broad look, things look fine. We will need to review it to ensure it's ready to get merged. We couldn't find enough time to review it, yet. Thanks for your understanding and the contribution.

**Comment by adarshmadrecha** [comment]
This is great. Been looking for this functionality for last 4 days.

**Comment by mstroeve** [comment]
@adarshmadrecha thanks hopefully the team will find time to review this PR 😄

**Comment by mstroeve** [comment]
@yusufkandemir is there anyway we can speedup this PR review process besides sponsoring 😄 ? We would really like to see this added in a nearby release.

**Comment by rstoenescu** [comment]
Thanks for contributing!
This will go into Quasar v2.16.8

**Pull request merged**
