### PR TITLE
Firebase docs

### PR DESCRIPTION
**Pull request by adamkpurdy**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [x] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] It's been tested on a Tauri app
- [x] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
This is the initial PR for the new Firebase section of docs.

### CODE REVIEW

**Comment by lombo75** [comment]
is this documentation going to be finished?

**Comment by adamkpurdy** [comment]
@lombo75 Working on it, looking to get the basic setup, email account creation, and login, Firestore bindings, and small sample apps that reflect those pieces before the year is out.

Have you checked out the #Firebase channel on the discord server?

**Comment by lombo75** [comment]
No, the only part that doesn't make sense to me is the 

export const handleOnAuthStateChanged = async (store, currentUser) => {
  const initialAuthStateSet = isAuthenticated(store)

 what is isAuthenticated an 
1. action? 
2. method in what file?
3. something else?

**Comment by adamkpurdy** [comment]
@lombo75 This is still preliminary, and it might change, but to answer your question directly it is a method in that same file just checking if the boolean has been already set in state.

```js
/**
 * @param  {Object} store - Vuex store
 */
export const isAuthenticated = (store) => {
  return store.state.auth.isAuthenticated
}
```

**Comment by lombo75** [comment]
I actually just have a routeGuard as a boot file, so was looking at your setup thanks for the clarification, makes a lot of sense now

export default ({ app, router, Vue }) => {
     router.beforeEach((to, from, next) => {
         firebase.auth().onAuthStateChanged(user => {

**Comment by adamkpurdy** [comment]
No problem, but please take this as preliminary. My other team members and I are still working on the best possible way to approach this.

**Comment by adamkpurdy** [comment]
Will be replaced with new PR

**Pull request closed without merging**
