### PR TITLE
Gallery Slider infinite scrolling and autoplay

### PR DESCRIPTION
**Pull request by danikane**
Gallery Slider infinite scrolling and autoplay. Complements PR #453

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
-  Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
-  No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

-  It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by danikane** [comment]
Oh, I see you already made that :) Really fast!

**Comment by rstoenescu** [comment]
Yeah :)))) Upgrade to v0.13.6. Just released it.

**Comment by danikane** [comment]
Nice, it was a simple one, but I had a fight with your linter :))

**Comment by rstoenescu** [comment]
Thanks for thinking of creating a PR, though!

**Pull request closed without merging**
