### PR TITLE
feat(QDate): multiple and range selection #5052

### LINKED ISSUE #5052: QDate multiple selection
Grouping #4815, #4727, #640, #4304, #1132, #1900 .

- add a way to select multiple dates in QDate

### PR DESCRIPTION
**Pull request by leoelz**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [x] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

The QDate `value` prop now accepts Array besides the original String when more than one date is selected, when it is a range of dates, the value has an Array inside of an Array with 2 elements: range start and range end.

Two boolean props are added: `multiple` and `range`, can be true each of one and both.

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
resolves #5052

### CODE REVIEW

**Comment by rossity** [comment]
Just wanted to come by and say that I need this right now in the project I'm working on and that this is FANTASTIC work @leoelz 

Excited to see the final result and merge into Quasar official

**Comment by leoelz** [comment]
Thank you @rossity, we must have patience, @rstoenescu [wrote](https://github.com/quasarframework/quasar/pull/7201#issuecomment-642547097) that will go on v1.13. 🚀

**Comment by rossity** [comment]
Sounds great, just wanted to let you know your work is appreciated.

**Comment by rstoenescu** [comment]
Awesome work. Will do a bit of polishing.
Feel free to contact me on Discord - would like to talk to you a bit.
This will go into v1.13.

**Pull request merged**
