### PR TITLE
fix(QTimeline): svg icons have incorrect size

### PR DESCRIPTION
**Pull request by Tofandel**
Fixes the regression introduced in #13651

**What kind of change does this PR introduce?** 

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on an Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

### CODE REVIEW

**Comment by pdanpdan** [comment]
Can you please port the fix for Qv1 also?

**Comment by rstoenescu** [comment]
Thanks for contributing!
Improved the fix (img icons had same issue). Ported to Q1 as well.

Will be available in Quasar v2.7.4

**Comment by bobintornado** [comment]
I think `img` icons are still having the same issue.

I replicated the same change in this PR.

https://github.com/quasarframework/quasar/pull/13903/files

**Comment by rstoenescu** [comment]
@bobintornado Which is why I pushed another commit on top of this PR specifically for img QIcons. If you have latest Quasar it should already work as intended.

**Comment by bobintornado** [comment]
@rstoenescu are you referring to release 2.7.5?
I encounter this issue when upgrading from 2.6.0 to 2.7.5.
I thought it is fixed too but I couldn't figure out what went wrong in my upgrading flow.
I monkey patch my project's app.css with the same fix and it worked.

Is there a related breaking change i missed? I think I probably did something wrong in my project

**Comment by Tofandel** [comment]
@bobintornado Check that you don't have 2 quasar versions at the same time by any chance `npm why quasar`

**Comment by bobintornado** [comment]
@Tofandel thanks for the tip! But looks like i don't have two versions 
```bash
quasar@2.7.5
node_modules/quasar
  quasar@"^2.7.5" from the root project
  peer quasar@"^2.6.0" from @quasar/app-vite@1.0.5
  node_modules/@quasar/app-vite
    dev @quasar/app-vite@"^1.0.5" from the root project
  peer quasar@"^2.0.0" from @quasar/vite-plugin@1.0.10
  node_modules/@quasar/vite-plugin
    @quasar/vite-plugin@"^1.0.9" from @quasar/app-vite@1.0.5
    node_modules/@quasar/app-vite
      dev @quasar/app-vite@"^1.0.5" from the root project
```

`npm ls --include=dev quasar` gives me 
```
├─┬ @quasar/app-vite@1.0.5
│ ├─┬ @quasar/vite-plugin@1.0.10
│ │ └── quasar@2.7.5 deduped
│ └── quasar@2.7.5 deduped
└── quasar@2.7.5
```

pretty confused about what is going on 🤔

**Comment by Tofandel** [comment]
On which element are you having the issue exactly? Check the css with debug tools and have a look, maybe there is another element that had the regression and was forgotten, or maybe you have your own styles on there conflicting with quasar's style

**Comment by bobintornado** [comment]
I am having trouble with the `img` element when wrapped `.q-icon` class, namely `.q-icon>img`.

I am expecting it should be 
```css
 width: 1em;
 height: 1em;
```

But it is 

```sass
width: 100%
height: 100%
```

On the dev branch (https://github.com/quasarframework/quasar/blob/dev/ui/src/components/icon/QIcon.sass#L25)

As a result, when using `q-icon` with a customized image, the `size` attribute is not working for me as expected. (my image icon are bigger than expected)

I put the following in my `app.css` and it works for me as expected when using `q-icon` with a customized image
```css
.q-icon>svg, .q-icon>img {
  width: 1em;
  height: 1em;
}
```

**Pull request merged**
