### PR TITLE
feat(docs) add whatsapp layout to gallery

### PR DESCRIPTION
**Pull request by lucasfernog**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

I believe this is a good example of using QLayout with the `container` prop, showing that we can build layouts that is more than just that sticky drawer on left and a toolbar on top.

If this is accepted and merged, the CDN should be updated with a screenshot. Here's the initial one:

2019-06-30_1911x942_screenshot

### CODE REVIEW

**Comment by rstoenescu** [comment]
Excellent!! Can you do a ~ 2000 x 1055px screenshot and add it to CDN pls?

**Comment by lucasfernog** [comment]
What kind of resolution is that LOL

**Comment by rstoenescu** [comment]
Let me do the screenshot.
Great job, man! Looks awesome.

**Comment by lucasfernog** [comment]
Thank you!

**Pull request merged**
