### PR TITLE
fix(docs) double submission on <enter>

### PR DESCRIPTION
**Pull request by nothingismagick**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/dev/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rstoenescu** [comment]
Denjell,

simulateSubmit() changes the variable bound to `loading`. It's not triggering the submit itself.
Also if it were to be removed, it should have been removed from the `<script>` part too.

**Comment by qmorek** [comment]
Hi @rstoenescu,
Correct me if I am wrong, we put simulateSubmit into @submit.prevent to handle form submission in this method and prevent page reload.
And if there is in q-btn
`@click="simulateSubmit"`
this method is called twice.
You can check this code pen:
https://codepen.io/qmorek/pen/bJMzpw?editors=1111
I have changed q-btn click method to simulateClick which just print 'clicked' to console.

You can click on button or use ENTER and both methods simulateSubmit and simulateClick are called.

**Comment by rstoenescu** [comment]
@qmorek Hi, this is because of a bug in QBtn which has been fixed in beta.18 (to be released tomorrow). The examples are correct.

**Comment by rstoenescu** [comment]
Ah, now I see. The form itself had a `@submit` event attached too. Sorry, merged this as it is valid.

**Pull request merged**
