### PR TITLE
Fix a prop name in the docs

### PR DESCRIPTION
**Pull request by louisameline**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: error in doc

### CODE REVIEW

**Comment by rstoenescu** [comment]
Hi,

Thanks for wanting to contribute.
It's recommended to specify prop names using dash (coming from Vue team).

**Comment by louisameline** [comment]
I didn't know that, thanks. The doc is not consistent though, maybe this rule should be applied everywhere at some point. Thank you

**Comment by rstoenescu** [comment]
Where are the places where you found it to be inconsistent?

**Comment by nothingismagick** [comment]
Well, if you find other cases of this please feel free to make a PR to get
it all up to snuff. With so many contributors and late nights we really
rely on the whole community to help!

Thanks again!!!

**Pull request closed without merging**
