### PR TITLE
Global configuration for internationalization of components

### PR DESCRIPTION
**Pull request by wagnereliakim**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/master/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Review by brucelane — CHANGES_REQUESTED** [review]
clearLabel and clear : Effacer
okLabel: Ok or Valider
noData: Aucune donnée à afficher.

**Comment by brucelane** [comment]
in french, months and day names should start with a capital letter

**Comment by wagnereliakim** [comment]
@brucelane done. Google translate... :see_no_evil:

**Comment by rstoenescu** [comment]
Nice. Will merge it and go one step further to add ability to dynamically change language at runtime. Good work!

**Comment by rstoenescu** [comment]
Pushed i18n branch for this. Seems like it requires a bit of work for the dynamic change.

**Comment by guyulmaz** [comment]
can you add this Turkish translation if possible

export const i18n = {
  dayNames: 'Pazar_Pazartesi_Salı_Çarşamba_Perşembe_Cuma_Cumartesi'.split('_'),
  monthNames: 'Ocak_Şubat_Mart_Nisan_Mayıs_Haziran_Temmuz_Ağustos_Eylül_Ekim_Kasım_Aralık'.split('_'),
  clearLabel: 'Temizle',
  okLabel: 'Tamam',
  cancelLabel: 'İptal',
  selectLabel: 'Seç',
  dataTable: {
    columns: 'Sütunlar',
    allCols: 'Tüm Sütunlar',
    rows: 'Satırlar',
    selected: {
      singular: 'öğe seçildi.',
      plural: 'öğeler seçildi.'
    },
    clear: 'Temizle',
    search: 'Ara',
    all: 'Tümü',
    noDataAfterFiltering: '<i class="material-icons">warning</i> Sonuç yok. Lütfen arama terimlerini düzeltiniz.',
    noData: '<i class="material-icons">warning</i> Gösterilecek veri yok.'
  }
}

**Comment by rstoenescu** [comment]
Make a PR on the i18n branch pls. Thanks!

**Pull request merged**
