### PR TITLE
feat(QDate) enhance disabling features

### PR DESCRIPTION
**Pull request by lucasfernog**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

Initially I wanted to allow disabling specific years from the Years view because I want to create an YearPicker app extension, but when i discussed it with the staff on Discord, some other features came out. This PR addresses:

- controling disabled years (`years` and `disabled-years` props)
- disabling Years view (`no-years` prop)
- disabling backward and forward navigation on Months and Years view (`no-backward-month-navigation`, `no-forward-month-navigation`, `no-backward-year-navigation`, `no-forward-year-navigation` props) *so users can disable going to future/past dates*

### CODE REVIEW

**Comment by lucasfernog** [comment]
PS: if theses changes are approved, i'm going to update API files and docs for it

**Comment by nothingismagick** [comment]
I can't really check the PR, but can you confirm that there are no breaking
changes?

**Comment by lucasfernog** [comment]
Yes I do

**Comment by lucasfernog** [comment]
Maybe I should write "months" and "disabled-months" instead of the navigation props

**Comment by lucasfernog** [comment]
And maybe I should disable all days in a year if the year is disabled... i will make those changes if Razvan think that this PR is a good idea

**Comment by lucasfernog** [comment]
Changed navigation disabling to month disabling (`months` and  `disabled-months` props)

**Pull request closed without merging**
