### PR TITLE
feat(app/capacitor): upgrade to capacitor 2.0, fixes #5823

### LINKED ISSUE #5823: EnableHttpsSelfSigned.enable prevents Capacitor plugins from working
If `EnableHttpsSelfSigned.enable(findViewById(R.id.webview));` is present in `MainActivity.java`, it will prevent Capacitor native plugins from working, since `EnableHttpsSelfSigned` class overrides the `WebViewClient` that Capacitor uses to inject the javascript that makes plugins work.

### PR DESCRIPTION
**Pull request by nklayman**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [x] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [x] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

This PR will use a new method to enable https support for capacitor. It is only available since version 1.5.1 of capacitor. In addition, new projects created will use capacitor 2.0. Other than the https issue, it will work with existing pre-2.0 capacitor projects. I can add in a check to use the old https method for pre-1.5.1 projects to mitigate the breaking change.

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

Dev/build process stays the same. Have not testing for IOS, someone has to before this gets merged. Also need someone to test that native plugins still work with https enabled.

### CODE REVIEW

**Comment by J3m5** [comment]
This is great, thank you!

You might want to change the hard coded path [here](https://github.com/quasarframework/quasar/blob/27092c4c23e907a53e5b627ff4884e672d6c8b6b/app/lib/capacitor/capacitor-config.js#L193) to the real ones, because the path is only valid if the capacitor or cordova id has not been modified.
If it has, the patch will no be applied.

**Comment by nklayman** [comment]
@J3m5 My latest commit should have fixed that issue, it uses a glob to automatically find the proper path. If you could test it out that would be awesome.

**Comment by J3m5** [comment]
I'll try to test it today and keep you posted.

**Comment by IlCallo** [comment]
@J3m5 hey there! Did you find the time to test this?

**Comment by J3m5** [comment]
Hey ! 
Unfortunately no, I've been quiet busy in the last few days. 
I'll try tomorrow and let you know.

**Comment by J3m5** [comment]
So, I've tested it, it handles the self signed certificate errors correctly but it still doesn't solve the problem of missing cordova and capacitor runtime in the index.html file that is served to the client.

Like I previously said in issue #6771, I don't think it is strictly related to the ssl errors, but it has more to do with two possible things:

1. The file served with https enabled in not the one that is modified by capacitor ( with the cordova and capacitor scripts injected)

2. The good file is served but the injection didn't happened

**Comment by J3m5** [comment]
I think we could merge this and deal with the ssl error in another PR to resolve the issues caused by the capacitor upgrade problems.

**Comment by rstoenescu** [comment]
Merging, testing, and adapting to q/app v2.

**Pull request merged**
