### PR TITLE
feat(docs) components API props grouped by category

### PR DESCRIPTION
**Pull request by lucasfernog**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/dev/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

This PR is related to #3813. 
The new API "category" field is now used to group component props, which are rendered with vertical QTabs. 
The categories are sorted alphabetically.
Each tab contains a QBadge indicating the number of related props.
When the user filters the API, if only one category contains found props, the current tab is changed to that.

Please let me know if there's something I should implement or change.

2019-04-06_846x787_screenshot

### CODE REVIEW

**Comment by nothingismagick** [comment]
I would personally prefer if the categories were left aligned instead of centered

**Comment by lucasfernog** [comment]
Like this @nothingismagick ? I still can't figure out how to float the QBadge and still use col-auto properly

2019-04-07_884x549_screenshot

**Comment by nothingismagick** [comment]
Nice. Maybe put the badge first and pad with a 0?

**Comment by lucasfernog** [comment]
Done @nothingismagick 
2019-04-07_836x442_screenshot

**Comment by nothingismagick** [comment]
While you're there can you wrap the display of the results from the section
in a scroll area?

**Comment by lucasfernog** [comment]
> While you're there can you wrap the display of the results from the section in a scroll area?

Done. On the future maybe we should change the whole API section to have a fixed height and a QScrollArea on the panels.

**Comment by nothingismagick** [comment]
Yeah, let's do it now.

>

**Comment by lucasfernog** [comment]
Much better now.

**Comment by nothingismagick** [comment]
Screenshot please?

**Comment by lucasfernog** [comment]
1_screenshot
2_screenshot

**Comment by rstoenescu** [comment]
Excellent work! Thank you for your efforts!

**Pull request merged**
