### PR TITLE
Broken link

### PR DESCRIPTION
**Pull request by turigeza**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe:
Typo
**Does this PR introduce a breaking change?** (check one)

- [  ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch

### CODE REVIEW

**Comment by rstoenescu** [comment]
Thanks!

**Comment by turigeza** [comment]
@rstoenescu  I have found a few more things they are all docs related ... shall I keep doing this tiny pull request or is it going to annoy the hell out of you : ) ? 
I mean I could just list them in an issue and let you all correct it as an alternative.  ?

**Comment by rstoenescu** [comment]
This PR has been merged already.
Please create a new PR and put all stuff in it. Are they URL related too?

**Comment by turigeza** [comment]
I know it was merged. Ok i will do pr for each as i find them. No they are
not url related mostly just small mistakes. I just wanted to make sure i am
not annoying you with these tiny tiny PRs

**Comment by rstoenescu** [comment]
@turigeza Make a PR with all the small things instead of multi small ones ;) Thanks for helping out!

**Pull request merged**
