### PR TITLE
feat: Add direction as a second parameter to the Slider's slide event.

### PR DESCRIPTION
**Pull request by dobromir-hristov**
Adds the direction of the current slide action to the Slider component.

### CODE REVIEW

**Comment by rstoenescu** [comment]
Merged. Thanks for this!

**Comment by dobromir-hristov** [comment]
I have to update the Docs.

**Comment by rstoenescu** [comment]
@dobromir-hristov just visit http://quasar-framework.org/components/slider.html and hit the pencil icon on the right of page title OR the "Suggest an edit on GitHub" at the bottom of page. Many thanks!

**Comment by dobromir-hristov** [comment]
Yeah, I just thought that being for v0.14 it used a special branch or something. Will do i there then.

**Comment by rstoenescu** [comment]
We're preparing for v0.14 release, so all "dev" branches are for v0.14 now. Thanks for taking care of documentation too!

**Pull request merged**
