### PR TITLE
Problems with Vue Dev tools

### PR DESCRIPTION
**Pull request by maarteNNNN**
Add docs to successfully see the registered component in the Vue Dev Tools.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/dev/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

While working with QDialog the component wasn't registering succesfully, putting this in the docs users might find it useful not encountering the problem as I had.

### CODE REVIEW

**Comment by panstromek** [comment]
Can you please elaborate more on what was your issue we were discussing? Razvan doesn't know anything about what we were talking about thx ;)

**Comment by nothingismagick** [comment]
Yeah, thanks - I was about to ask.

**Comment by rstoenescu** [comment]
This is a Vue devtools bug. I'll see if I got some time to report it with proper info on it.

**Comment by maarteNNNN** [comment]
Screenshot from 2019-03-12 10-23-52
The QDialog wasn't showing up as a component in the Vue Dev Tools. Forcing a reload in the upper right corner resolved the issue. @rstoenescu This bug is definitely related to a Vue devtools bug.

**Comment by nothingismagick** [comment]
One thing that I really like using is the vue-devtools standalone electron
interface. Maybe try that out...

>

**Comment by panstromek** [comment]
The way QDialog and other popovers work is not intuitive for newcomers, and combined with the fact that there is a bug in devtools makes it really confusing.

I know that this is not really our problem but I asked @maarteNNNN to make a docs PR with some notice about it, so other developers don't get lost trying to figure it out. I thought it could be helpful for somebody ;)

**Pull request closed without merging**
