### PR TITLE
Remove workaround for bug in Electron 6-8

### PR DESCRIPTION
**Pull request by rotu**
**What kind of change does this PR introduce?** 

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [x] Yes
- [ ] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on an Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by pdanpdan** [comment]
Please also remove the imports that are only used in the removed blocks

**Comment by rotu** [comment]
This is technically a breaking change but Electron 8 has been EOL since 2020.

**Comment by rotu** [comment]
@pdanpdan done.

How do you run the linters? I'm getting failures for unrelated reasons:

```
yarn workspace @quasar/app-vite lint
yarn workspace v1.22.19
yarn run v1.22.19
$ eslint --ext .js ./ ./bin/quasar --fix --report-unused-disable-directives

C:\Users\dan\Source\quasar\app-vite\lib\config-tools.js
  3:46  error  "@quasar/vite-plugin" is not found  n/no-missing-require

C:\Users\dan\Source\quasar\app-vite\lib\quasar-config-file.js
  7:40  error  "@quasar/vite-plugin" is not found  n/no-missing-require

✖ 2 problems (2 errors, 0 warnings)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: C:\Users\dan\scoop\apps\nodejs-lts\current\node.exe
Arguments: C:\Users\dan\AppData\Local\node\corepack\yarn\1.22.19\lib\cli.js lint
Directory: C:\Users\dan\Source\quasar\app-vite
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
```

**Comment by pdanpdan** [comment]
LGTM.
For the moment i also have problems running the dev branch, i think there are some changes in progress.
Let's wait for @rstoenescu opinion on this

**Comment by rstoenescu** [comment]
Awesome! Thanks for contributing!

Both q/app-vite and q/app-webpack are under heavy fire at the moment, but linting should work regardless.

**Pull request merged**
