### PR TITLE
[v1] Add Persian calendar to QDate

### PR DESCRIPTION
**Pull request by behnoodk**
As discussed in #3359 I have added Persian calendar to QDate based on `persian` property in `date` section of `lang` file.
When `$q.lang.date.persian === true` QDate expects a valid Persian date as its model value in the format `YYYY/MM/DD` and will set the model as a string in the format `YYYY/MM/DD`, exactly like default behavior.
Right now `fa-IR` is set to `persian=true` because this is the only locale that I am sure the official calendar system is Persian (Jalaali).
I have tried to keep the changes to minimum and have not changed any of the original code for Gregorian (default) calendar.
For calculations needed for conversion between Persian and Gregorian dates the file `quasar/src/components/datetime/persian.js` was added.
I have also updated the file `quasar/dev/components/form/date.vue` to be able to test the new feature. All `QDate` instances in the file work properly and as expected with Persian calendar system.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/dev/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rstoenescu** [comment]
Very good PR! Thank you for your work on this!

Will merge as is but push some changes to the way it works.
Thinking a bit that since it requires another model, this would break the app when users switch from one Quasar language pack to/from fa-ir. So I'll add a "calendar" prop (with possible values: "gregorian" - default, and "persian") and remove the "persian" prop from the language pack itself.

Sounds good?

**Comment by behnoodk** [comment]
Yes! I believe that's much better. It is clearer and since developer has to explicitly set the `calendar` prop to `persian`, there won't be any confusion when setting/getting the model.
Also different calendars can be used within the same app.

Thank you.

**Comment by rstoenescu** [comment]
No, thank you for this PR!

**Comment by rstoenescu** [comment]
@behnoodk Can you DM on Discord please? Got a question and want to finish this ASAP.

**Pull request merged**
