### PR TITLE
QTootip with arrow #2105

### LINKED ISSUE #2418: [Suggestion] Add arrows to the tooltip popup.
Currently the tooltip looks like this:

image

How about it look like this?

image

Scott

### Software version

Quasar:
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

### LINKED ISSUE #2518: error in documantation
Documentation error:
let date = addToDate(new Date(), { days: 7, months: 1 })

correct:
let date = addToDate(new Date(), { days: 7, month: 1 })

months are more semantic but Date Object has methods GetMonth and setMonth

### PR DESCRIPTION
**Pull request by smolinari**
This is my attempt at adding arrows to the tool tip. 

It only adds the arrow, when the tooltip popup is directly above, below, to the right or left. I didn't know how to handle the other locations. 

Scott

close #2418 

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/dev/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by nothingismagick** [comment]
Please add a screenshot of the results.

**Comment by nothingismagick** [comment]
Well, personally I dislike the "iOS" theme.

**Comment by darkscript** [comment]
This would be a great option, the option and be also in the q-popover, related issue #2104 and #2105

**Comment by smolinari** [comment]
@darkscript - Sorry. I should have taken your issue as the reference and not created a new one. I wasn't aware this was already suggested. 

Scott

**Comment by rstoenescu** [comment]
Wish it were this easy :) Made some adjustements to it.

It's a good start, but:
* Tooltip can get repositioned in which case the arrow will need updating too
* The arrow needs positioning according to the target; not always centered vertically or horizontally, otherwise:

download

**Comment by nothingismagick** [comment]
Would it makes sense maybe to find some middle ground, where if the dev chooses to use the arrow that the tooltip is then centered?

**Comment by rstoenescu** [comment]
Not really. Imagine devs adding a tooltip on a small dot area which is placed leftmost of screen :)

**Comment by nothingismagick** [comment]
Well in that case the arrow would be on the left side of the tooltip of course - and in the middle ...

**Comment by emahuni** [comment]
Can this be added to the Menu component as well as an option. This'd be great to have as an option on the menu component. It'd just be placed on the center, or corners depending on the positioning options.

**Comment by smolinari** [comment]
No it didn't, because the solution doesn't work in a lot of situations. I'm not a great front end developer. 😊 

Scott

**Comment by nothingismagick** [comment]
We closed this issue for 0.17 because there was not a really efficient way to do it computed via properties and it is basically purely edge cases. I do have an idea about how to do it using `getBoundingClientRect()` that measures the position and size of the item calling the tooltip and the position of the tooltip itself, but I can't promise that it will really work because of problems measuring margins.

**Pull request closed without merging**
