### PR TITLE
fix(create): update standard lint dependencies, fix #12872

### LINKED ISSUE #12872: Error bootstraping new project
### What happened?

Erro while bootstraping new quasar app

I was just trying to install fresh quasar app using npm init quasar and got this error

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: front@0.0.1
npm ERR! Found: eslint@8.11.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^8.10.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^7.12.1" from eslint-config-standard@16.0.3
npm ERR! node_modules/eslint-config-standard
npm ERR!   dev eslint-config-standard@"^16.0.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/zim32/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zim32/.npm/_logs/2022-03-21T12_43_30_841Z-debug-0.log

```

### What did you expect to happen?

No errors during npm init quasar
Ready to use fresh project

### Reproduction URL

https://codepen.io/pen?&editors=101

### How to reproduce?

1. npm init quasar
2. Select Standart linter

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app)

### Platforms/Browsers

_No response_

### Quasar info output

```shell
Operating System        Linux(5.13.0-30-generic) - linux/x64
NodeJs                  14.18.2

Global packages    
  NPM                   8.3.0
  yarn                  Not installed
  @quasar/cli           1.3.1
  @quasar/icongenie     Not installed
  cordova               Not installed

Networking         
  Host                  hostname
  eth0                  172.18.0.4
  eth1                  172.27.0.7
```

### Relevant log output

```shell
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i' ]
1 info using npm@8.3.0
2 info using node@v14.18.2
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 3ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/zim32/www/code/public/front/.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:/home/zim32/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 8ms
19 timing npm:load:configload Completed in 9ms
20 timing npm:load:setTitle Completed in 1ms
21 timing config:load:flatten Completed in 2ms
22 timing npm:load:display Completed in 3ms
23 verbose logfile /home/zim32/.npm/_logs/2022-03-21T12_47_59_610Z-debug-0.log
24 timing npm:load:logFile Completed in 3ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 16ms
28 timing arborist:ctor Completed in 1ms
29 timing arborist:ctor Completed in 0ms
30 timing idealTree:init Completed in 11ms
31 timing idealTree:userRequests Completed in 0ms
32 silly idealTree buildDeps
33 silly fetch manifest @quasar/extras@^1.0.0
34 http fetch GET 200 https://registry.npmjs.org/@quasar%2fextras 2137ms (cache revalidated)
35 silly fetch manifest core-js@^3.6.5
36 http fetch GET 200 https://registry.npmjs.org/core-js 123ms (cache revalidated)
37 silly fetch manifest quasar@^2.6.0
38 http fetch GET 200 https://registry.npmjs.org/quasar 1069ms (cache revalidated)
39 silly fetch manifest vue@^3.0.0
40 http fetch GET 200 https://registry.npmjs.org/vue 119ms (cache revalidated)
41 silly fetch manifest vue-router@^4.0.0
42 http fetch GET 200 https://registry.npmjs.org/vue-router 125ms (cache revalidated)
43 silly fetch manifest @babel/eslint-parser@^7.13.14
44 http fetch GET 200 https://registry.npmjs.org/@babel%2feslint-parser 124ms (cache revalidated)
45 silly fetch manifest @babel/core@>=7.11.0
46 http fetch GET 200 https://registry.npmjs.org/@babel%2fcore 124ms (cache revalidated)
47 silly fetch manifest eslint@^8.10.0
48 http fetch GET 200 https://registry.npmjs.org/eslint 109ms (cache revalidated)
49 silly fetch manifest eslint-plugin-vue@^8.5.0
50 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-vue 110ms (cache revalidated)
51 silly fetch manifest eslint-webpack-plugin@^3.1.1
52 http fetch GET 200 https://registry.npmjs.org/eslint-webpack-plugin 125ms (cache revalidated)
53 silly fetch manifest webpack@^5.0.0
54 http fetch GET 200 https://registry.npmjs.org/webpack 111ms (cache revalidated)
55 silly fetch manifest eslint-config-standard@^16.0.2
56 http fetch GET 200 https://registry.npmjs.org/eslint-config-standard 915ms (cache revalidated)
57 silly fetch manifest eslint@^7.12.1
58 timing idealTree Completed in 5280ms
59 timing command:i Completed in 5291ms
60 verbose stack Error: unable to resolve dependency tree
60 verbose stack     at Arborist.[failPeerConflict] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1362:25)
60 verbose stack     at Arborist.[loadPeerSet] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1328:34)
60 verbose stack     at async Arborist.[buildDepStep] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:935:11)
60 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:216:7)
60 verbose stack     at async Promise.all (index 1)
60 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:149:5)
60 verbose stack     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:157:5)
60 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:66:5)
61 verbose cwd /home/zim32/www/code/public/front
62 verbose Linux 5.13.0-30-generic
63 verbose argv "/usr/bin/node" "/usr/bin/npm" "i"
64 verbose node v14.18.2
65 verbose npm  v8.3.0
66 error code ERESOLVE
67 error ERESOLVE unable to resolve dependency tree
68 error
69 error While resolving: front@0.0.1
69 error Found: eslint@8.11.0
69 error node_modules/eslint
69 error   dev eslint@"^8.10.0" from the root project
69 error
69 error Could not resolve dependency:
69 error peer eslint@"^7.12.1" from eslint-config-standard@16.0.3
69 error node_modules/eslint-config-standard
69 error   dev eslint-config-standard@"^16.0.2" from the root project
69 error
69 error Fix the upstream dependency conflict, or retry
69 error this command with --force, or --legacy-peer-deps
69 error to accept an incorrect (and potentially broken) dependency resolution.
69 error
69 error See /home/zim32/.npm/eresolve-report.txt for a full report.
70 verbose exit 1
71 timing npm Completed in 5467ms
72 verbose unfinished npm timer reify 1647866879775
73 verbose unfinished npm timer reify:loadTrees 1647866879784
74 verbose unfinished npm timer idealTree:buildDeps 1647866879797
75 verbose unfinished npm timer idealTree:#root 1647866879797
76 verbose code 1
77 error A complete log of this run can be found in:
77 error     /home/zim32/.npm/_logs/2022-03-21T12_47_59_610Z-debug-0.log
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by IlCallo**
**What kind of change does this PR introduce?** 

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch (or `v[X]` branch)
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**
Reference: https://github.com/quasarframework/quasar-starter-kit/issues/167
Changes to quasar-v2/ts-webpack/BASE/quasar.config.js remove some TS linting errors

### CODE REVIEW

**Comment by rstoenescu** [comment]
This clashed with Yusuf's PR, so recreated it (was easier) and pushed it then released it.
Nice finding for the node eslint plugin!

**Comment by IlCallo** [comment]
@rstoenescu  no problem, but please integrate these changes too (or any comment inside those empty functions, or comment the whole empty functions altogether), or people creating a webpack + TS + ESLint will have linting errors OOB

image

**Comment by rstoenescu** [comment]
@IlCallo can you push a commit for this with the original lines commented out pls? Also, bump the version of create-quasar.

**Comment by IlCallo** [comment]
Done

**Pull request closed without merging**
