### PR TITLE
feat(QSelect): dialog - add close icon; add class and style; open when typing in field; fix focus on field; do not auto show popup on focus #6523, #6858, #8592

### PR DESCRIPTION
**Pull request by pdanpdan**
#6523, #6858, #8592

### CODE REVIEW

**Comment by mam-ijinus** [comment]
hi, 

do you know, when this branch will be merged ?

Thanks

**Comment by pdanpdan** [comment]
@mam-ijinus  You can try a preview release.

In package.json replace `quasar` dependency with:
`"quasar": "https://github.com/pdanpdan/quasar#quasar-pdan-v1.15.5-beta.17"`

Then do a yarn or npm install and start the app again.

Please report if you find something not working.

**Comment by mam-ijinus** [comment]
> @mam-ijinus You can try a preview release.
> 
> In package.json replace `quasar` dependency with:
> `"quasar": "https://github.com/pdanpdan/quasar#quasar-pdan-v1.15.5-beta.17"`
> 
> Then do a yarn or npm install and start the app again.
> 
> Please report if you find something not working.

I will try this today, thanks.

**Comment by mam-ijinus** [comment]
when try `yarn dev`:

```
App · ⚠️  Extension(qdatetimepicker): is not compatible with quasar v1.15.5-beta.17. Required version: ^1.0.0
```

Same with q-iconpicker and a personnal component extension.

I presume that beta version is no reconize for the version check.

There is a way to bepass the check ?

**Comment by cyhnkckali** [comment]
Hello Community, At what stage is the latest situation in development?

**Pull request closed without merging**
