### PR TITLE
Update Google Material icons fonts, fix: #11234

### LINKED ISSUE #11234: Material icons are out-dated
**Is your feature request related to a problem? Please describe.**

I can't use `question_mark` of Google Material Design Icons. This should be a valid icon: https://fonts.google.com/icons?selected=Material+Icons&icon.query=question+mark. 

Example use-case:

```html
<q-btn flat dense icon="question_mark" class="q-mr-sm" />
```

**Describe the solution you'd like**

I think we should update the css/font.

**Additional context**

And why not update the other icon packs as well?

### PR DESCRIPTION
**Pull request by melroy89**
Fixed #11234

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [x] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

It's not really a bug or a feature, it's just out of date.

### CODE REVIEW

**Comment by hawkeye64** [comment]
Hi, this is not necessary. We have an automated build system for retrieving the current woff/woff2 and SVG files, that I try to run every Sunday.
Your fixes should be contained in this release: https://github.com/quasarframework/quasar/releases/tag/%40quasar%2Fextras-v1.11.5

**Comment by melroy89** [comment]
Still strange why I get a different binary in this PR (the woff files are not binary identical).

**Comment by melroy89** [comment]
Anyway, maybe update the package.json file as well:

https://github.com/quasarframework/quasar/blob/dev/ui/package.json#L66

Bump `@quasar/extras` to v1.11.5

**Comment by rstoenescu** [comment]
@danger89 

Notice 1) the caret in the version there (means install latest v1 quasar/extras) and 2) notice it's a devDependency so it doesn't matter when you install the UI package in your app; 3) All that matters is that you upgrade quasar/extras in your app (it's a direct dependency of your app).

**Comment by melroy89** [comment]
@rstoenescu I understand. For some reason npm update doesn't update to the latest quasar or quasar/extras. I tried: ` npm update @quasar/extra`

image

Strange, right?

**Comment by melroy89** [comment]
So the only fix was to force pick a version number, so I ran: `npm install @quasar/extras@1.11.5`, did solve the problem. I don't know why npm didn't want to upgrade.

**Pull request closed without merging**
