### PR TITLE
V1 :  Add new language | IsoName: 'bn' | NativeName: বাংলা

### PR DESCRIPTION
**Pull request by ctpli**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

I have added the translated and zipped bn.js file as recommended please download : [bn.zip](https://github.com/quasarframework/quasar/files/7012047/bn.zip)

### CODE REVIEW

**Comment by hawkeye64** [comment]
Thanks for the PR, but it cannot be accepted with this many conflicts. I suggest you create a new branch from the latest and try again.

Also, is there no short form of the months?
Also, short days has Thursday twice and some day names are not short.
image

**Comment by hawkeye64** [comment]
There are some issues with the file you provided:

on `daysShort`, Thursday is provided twice (missing Wednesday). Also, not all day names are shortened as expected.
on `monthShort`, all names are still long, except for `Me` (May?)

image

**Comment by ctpli** [comment]
Hi @hawkeye64 , 


I can confirm that,

1. **daysShort** is absolutely okay in Bengali, but the tool used to convert to English is done incorrectly. I have indicated the portion for Wednesday you may try to convert to English only that portion. 

image


2.  **monthShort**:  for the Bengali language, the short name is not available for months. so long names and short names fr months are the same. 

Please advice.

**Comment by hawkeye64** [comment]
Thanks for the info. Can you make this into an actual PR?

**Pull request closed without merging**
