### PR TITLE
fix: #8269 (@quasar/app) adding path.join to build path strings.

### PR DESCRIPTION
**Pull request by Saeid-Za**
**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] It's submitted to the `dev` branch and _not_ the `master` branch
- [X] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by pdanpdan** [comment]
As you are at it, can you please check if there is any other check using hard-coded paths in app?

**Comment by Saeid-Za** [comment]
I've almost checked every line of `@quasar/app` with this Regex: `'/'^(.+)\/([^/]+)$`.
I was not able to find anything directly using hard-coded paths, but there were some suspicious lines. I list them below, for further investigations.

- quasar/app/lib/app-extension/Extension.js (line 64-75)

**Comment by pdanpdan** [comment]
Thank you, I'll take a look at them also.

**Comment by rstoenescu** [comment]
Thank you for contributing!

**Pull request merged**
