### PR TITLE
fix(types): Added proper type for QForm submit event

### PR DESCRIPTION
**Pull request by soulsam480**
**What kind of change does this PR introduce?** 

- [X] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [X] No

**The PR fulfills these requirements:**

- [X] It's submitted to the `dev` branch (or `v[X]` branch)
- [X] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by soulsam480** [comment]
Currently the submit event emitted by QForm does pass the event object to the handler but it's not defined in the types. As [VeeValidate](https://vee-validate.logaretm.com/v4/) depends upon the submit event for it's [handleSubmit](https://vee-validate.logaretm.com/v4/api/form#default) slot prop, it throws type error as the event is undefined. 
image

**Comment by rstoenescu** [comment]
Hi,

Thanks for contributing!
This will go into Quasar v2.5.4.

It breaks the build, but will fix it in a subsequent commit.

**Comment by soulsam480** [comment]
> 

Thanks, I'm sorry for the build failure. I'm not 100% acquainted with the type generation system of quasar. Will try to look into it.

**Comment by rstoenescu** [comment]
No problem. Thanks for PRing!

**Pull request merged**
