### PR TITLE
fix: Duplicated process after main or render process files reloaded

### PR DESCRIPTION
**Pull request by yarikdevcom**
**What kind of change does this PR introduce?** 

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [x] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**
Tested on Mac OS 12.1, M1 Mac mini

### CODE REVIEW

**Comment by rstoenescu** [comment]
Hi @mortyspace ,

Thanks for contributing!
Can you detail more on how to reproduce the issue? Just want to make sure this is the right fix, because it doesn't feel right at the moment. Thanks in advance!

**Comment by yarikdevcom** [comment]
Here is a video and log. Probably on M1 process starts very fast or triggering change on both files.
https://www.dropbox.com/s/zw1it2il6gqoq82/Screen%20Recording%202022-01-29%20at%2015.44.12.mov?dl=0

```
morty@Mortys-Mac-mini implmanager % quasar dev -m electron

 Dev mode.......... electron
 Pkg quasar........ v2.4.13
 Pkg @quasar/app... v3.3.1
 Pkg webpack....... v5
 Debugging......... enabled

 Configured browser support (>= 89.34% of global marketshare):
 · Chrome for Android >= 97
 · Firefox for Android >= 95
 · Android >= 97
 · Chrome >= 88
 · Edge >= 94
 · Firefox >= 87
 · iOS >= 12.0-12.1
 · Opera >= 78
 · Safari >= 13

 App • Chaining "Renderer" Webpack config
 App • Chaining "Preload" Webpack config
 App • Chaining "Main" Webpack config
 App •  WAIT  • Compiling of "Renderer" in progress...
 App •  DONE  • "Renderer" compiled with success • 3312ms



 App •  READY  • Compiled: "Renderer"

 App •  WAIT  • Compiling of "Main" in progress...
 App •  WAIT  • Compiling of "Preload" in progress...
 App •  DONE  • "Main" compiled with success • 62ms
 App •  DONE  • "Preload" compiled with success • 60ms



 App •  READY  • Compiled: "Renderer", "Main", "Preload"

 App • Running "/Users/morty/Projects/hj/implmanager/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron --inspect=5858 /Users/morty/Projects/hj/implmanager/.quasar/electron/electron-main.js"

Debugger listening on ws://127.0.0.1:5858/579dbe67-c81b-4c60-8e4a-de837342c9cd
For help, see: https://nodejs.org/en/docs/inspector
 App •  WAIT  • Compiling of "Main" in progress...
 App •  DONE  • "Main" compiled with success • 56ms



 App •  READY  • Compiled: "Renderer", "Main", "Preload"

 App • Shutting down Electron process...
 App •  WAIT  • Compiling of "Main" in progress...
 App •  DONE  • "Main" compiled with success • 27ms



 App •  READY  • Compiled: "Renderer", "Main", "Preload"

 App • Running "/Users/morty/Projects/hj/implmanager/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron --inspect=5858 /Users/morty/Projects/hj/implmanager/.quasar/electron/electron-main.js"


 App • Running "/Users/morty/Projects/hj/implmanager/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron --inspect=5858 /Users/morty/Projects/hj/implmanager/.quasar/electron/electron-main.js"

Debugger listening on ws://127.0.0.1:5858/b3b65795-1040-4c9b-82de-9d2f28d7d1d5
For help, see: https://nodejs.org/en/docs/inspector
Starting inspector on 127.0.0.1:5858 failed: address already in use
 App •  WAIT  • Compiling of "Main" in progress...
 App •  DONE  • "Main" compiled with success • 51ms



 App •  READY  • Compiled: "Renderer", "Main", "Preload"

 App • Shutting down Electron process...
 App •  WAIT  • Compiling of "Main" in progress...
 App •  DONE  • "Main" compiled with success • 25ms



 App •  READY  • Compiled: "Renderer", "Main", "Preload"

 App • Running "/Users/morty/Projects/hj/implmanager/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron --inspect=5858 /Users/morty/Projects/hj/implmanager/.quasar/electron/electron-main.js"

Starting inspector on 127.0.0.1:5858 failed: address already in use

 App • Running "/Users/morty/Projects/hj/implmanager/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron --inspect=5858 /Users/morty/Projects/hj/implmanager/.quasar/electron/electron-main.js"

Starting inspector on 127.0.0.1:5858 failed: address already in use



 App • ⚠️  Electron process was killed. Exiting...

morty@Mortys-Mac-mini implmanager % 
```

**Comment by yarikdevcom** [comment]
Probably if both file changed we have race condition on creating process

**Comment by yarikdevcom** [comment]
I saved only 1 file, editor VSCode

**Comment by rstoenescu** [comment]
Thank you for providing the details.
Hope you don't mind, but decided to go on a more thorough refactoring to ensure the right things happen when reload is needed. https://github.com/quasarframework/quasar/commit/716c88aa0245c59623f6d47014b4cf816e8e997c

This will go into q/app v3.3.2

**Comment by yarikdevcom** [comment]
NP, thank you!

**Pull request closed without merging**
