### PR TITLE
Add cursor-pointer class when @click is defined on QTr

### PR DESCRIPTION
**Pull request by Propaganistas**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
This PR is a continuance of https://github.com/quasarframework/quasar/issues/5849
When there's a @click listener on QTr, auto-add the `cursor-pointer` class.

### CODE REVIEW

**Comment by rstoenescu** [comment]
Thanks for contributing!

**Comment by rstoenescu** [comment]
This will go into upcoming v1.8.0

**Comment by rstoenescu** [comment]
Hi,

I'm sorry, but I've reverted the change. Please manually add the "cursor-pointer" class. After all, devland is the place where you already know that you are going to have a listener attached so there's no reason to add code in Quasar (which also bumps up the number of Vue renders, so bad for perf). Sorry for any inconveniences.

**Comment by Propaganistas** [comment]
Just out of curiosity: how does this reasoning scale with the changes you made in https://github.com/quasarframework/quasar/issues/5849 ?

**Comment by rstoenescu** [comment]
For the issue in the ticket, there's no other way to provide this functionality other than what I've done for it. But when it comes to attaching directly to a low-level component, such as QTr, it really makes no sense to decrease runtime speed when in devland you already know u're attaching a listener to it. Why not then check for dblclick listener also? Why not add this to all Quasar components so that there won't be inconsistencies? It's pretty obvious why.

**Pull request merged**
