### PR TITLE
Fix sass deprecation warning

### PR DESCRIPTION
**Pull request by bartduisters**
A community member mentioned a deprecation warning in SASS.
This commit migrates the SASS Division: https://sass-lang.com/documentation/breaking-changes/slash-div

### CODE REVIEW

**Comment by rstoenescu** [comment]
Hi,

Thanks for contributing!
This has been discussed many times. The "sass" package needs to be pinned to v1.32.12 otherwise, indeed some deprecation warnings will appear. However, it is not easy to convert to the new syntax without adding breaking changes to our developer's apps (a definitely no-go) -- hence the pinning of the "sass" package which should not be touched (manually installed) by our devs (supplied by Quasar CLI).

**Comment by rstoenescu** [comment]
The pinning is also explained in the docs.

**Comment by bartduisters** [comment]
Alright. I mentioned it to the community.
However, I don't find v1.32.12 referenced in the docs, if you have the link available, it's handy to have as a response on this issue.

**Comment by MilosPaunovic** [comment]
> Alright. I mentioned it to the community. However, I don't find v1.32.12 referenced in the docs, if you have the link available, it's handy to have as a response on this issue.

https://quasar.dev/start/vite-plugin#installation - Check the green tip.

**Comment by bartduisters** [comment]
That page doesn't pop up in the search results when looking for 'sass'. Which is what I tried to find the page :D

**Pull request closed without merging**
