### PR TITLE
[post v0.15] Modal auto sizing and clean up flex box #1298

### PR DESCRIPTION
**Pull request by realcarbonneau**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/master/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

As discribed in #1298, the Modal Dialog collapses when a minimum size has not be specified.  This corrects the problem and also adds flexibility for the dialog windows to grow with it's content without requiring a minimum size.   The .col flex-basis 0 (flex.styl) has been removed since it was causing flex boxes to collapse under certain conditions, in particular in this case.

See the video below of the flexible modal working.

modalfixed

### CODE REVIEW

**Comment by rstoenescu** [comment]
This needs a careful consideration. Will take care of it tomorrow. Thanks for offering a PR!

**Comment by realcarbonneau** [comment]
I understand, the removal of "flex-basis 0" of.col (flex.styl)" has the widest risk side effects, but I see other places where forcing the flex-basis it causing problems.

**Comment by rstoenescu** [comment]
Please document the other scenarios here. This helps us a lot.

**Comment by realcarbonneau** [comment]
The video below is using the modal from the qusar dev branch. I manually modify the classes and style.  We can see that the position:absolute and the flex-basis:0 is breaking the flexbox flow.  Once these are removed, then we can have clean placement using only flexbox as can be seen at the end of the video.  The final result is what my correction provides.

modalflexboxcollapsewalkthrough

**Comment by realcarbonneau** [comment]
Here is another example of "flex-basis: 0" causing problems (video below). It seems like "width: 100%" was imposed for columns to fix the side effects of "flex-basis: 0". There is no reason to always override flex-basis and width of columns.  "flex-basis: 0" should only be imposed when absolute sizing is required.  The flexbox could be much better used in many places to reduce the code complexity and improve maintenance.  For example, there are many places where 100vh is used, which breaks subsequent relative height usage, and make the use less flexible.  One specific example is the layout, in general it could be cleaned up and made simpler by leveraging the flexbox.

flexbasis0problems

**Comment by realcarbonneau** [comment]
Just as a reminder, the difficult question in this PR is the removal of the imposed "flex-basis 0"

**Comment by rstoenescu** [comment]
Did a test. Breaks too many things. Postponing this for after v0.15.

**Comment by realcarbonneau** [comment]
Thank you for your feedback.  I have reviewed and adjusted this PR, the changes are now be isolated only to the QModal and QModalLayout.  I have also re-tested with the demo/tests and did not find any side effects.  

If you want the QModalLayout to be used outside of a QModal without my changes, I can add a correction a check for that.

Also, please advise me of any side effects you observed and I will correct them.

This is an important PR, when I develop, I don't want to have to specify the Modal size in most cases.  I want it to adjust to the content and the window. 

I will be maintaining this PR and keeping it up to date and using it within my mini-fork.

**Comment by dietrichg** [comment]
Exactly what I need as well. Any updates on this?

**Comment by rstoenescu** [comment]
@dietrichg Already in next Quasar version ;)

**Comment by dietrichg** [comment]
Oh, awesome. Any docs on this yet? How do i use it?

**Comment by rstoenescu** [comment]
@dietrichg Next version means it's not released yet :)

**Comment by dietrichg** [comment]
Ah darn. Thought you meant v.16 since this post was v.15. Awesome. I'll make a temp fix til then! Thanks

**Comment by aronluc** [comment]
@dietrichg 
Can you please post your temp fix?

**Pull request closed without merging**
