### PR TITLE
feat: Gitlab Continuous Integration Build yml Sample

### PR DESCRIPTION
**Pull request by obonyojimmy**
Added sample gitlab.yml for continous cordova builds

Continous intergration is un-evitable in any dev code setup, this sample gitlab-ci.yml
shows how one can make a cordova build right from gitlab repo plus also show test coverage
for the build

### CODE REVIEW

**Comment by rstoenescu** [comment]
Hi, thanks for taking time do a PR!

But not sure what you are trying to achieve. Would this be something for [Quasar app template repo](https://github.com/quasarframework/app-template-default) rather than Quasar's repo?

**Comment by obonyojimmy** [comment]
Thanks for feedback , ah yes this should go to the template app repo , let me rectify to the template app repo.

**Comment by obonyojimmy** [comment]
Have made a new PR on app-template-default

**Comment by rstoenescu** [comment]
Thanks. Closing this PR here then.

**Pull request closed without merging**
