### PR TITLE
FEAT (input fields): add input fields including validation / messages / state / floating labels

### PR DESCRIPTION
**Pull request by CookieJon**
FEAT (input fields): add input fields including validation / messages / state / floating labels

add input fields including validation / messages / state / floating labels

Addresses issues #174, #237

### CODE REVIEW

**Comment by smolinari** [comment]
Glad to see you are still with us! 😄 

Scott

**Comment by fsgiudice** [comment]
Excellent!

**Comment by CookieJon** [comment]
Yes, still here :-) but - typically - I've just noticed some minor bugs after I issued the pull request.  I'll get on 'em today.

**Comment by AGPDev** [comment]
Nice,waiting... +1

**Comment by rstoenescu** [comment]
Targeting v0.14 for forms.

**Pull request closed without merging**
