### PR TITLE
Pass current route in the btn mixin to router resolve

### PR DESCRIPTION
**Pull request by dmitry**
**What kind of change does this PR introduce?** (check at least one)

- [x] Feature

**Does this PR introduce a breaking change?** (check one)

- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)

**Other information:**

QRouteTab has the following code: 

```
        current = this.$route,
        { href, location, route } = this.$router.resolve(this.to, current, this.append),
```

It would be great to have the same for the btn when passing to `:to`.

### CODE REVIEW

**Comment by dmitry** [comment]
@rstoenescu please checkout this change. It's really simple but it allows to see current route in extended router resolver.

**Comment by dmitry** [comment]
@rstoenescu please let me know if anything missing here.

**Comment by rstoenescu** [comment]
Hi @dmitry 

Thanks for contributing!

The [signature](https://router.vuejs.org/api/#router-resolve) of the $router.resolve() method specifies that the second parameter is the current route by default anyway. So wondering why you think it should be explicitly added?

**Comment by dmitry** [comment]
@rstoenescu thank you for the answer.

`QRouteTab` has

```javascript
{ href, location, route } = this.$router.resolve(this.to, current, this.append),
```

I think `q-btn` component should have the same code passing current route into the `resolve` function.

Thanks to your comment, I've fixed an issue without that change. I've extended `$router.resolve()` but forgot to to add `this.history.current` for the current if it's missing.

**Comment by yusufkandemir** [comment]
Thanks for contributing, this is no longer needed. And now, every component that interacts with the router links uses the `useRouterLink` composable. So, they pretty much have a unified behavior. Also, a lot about Quasar, Vue, and Vue Router has changed in 2.5 years. So, I am closing this PR.

**Pull request closed without merging**
