### PR TITLE
Update QInput.vue

### PR DESCRIPTION
**Pull request by alexdee2007**
Add "upper-case" props to q-input

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by alexdee2007** [comment]
As vue2 deprecated two-way filters it would be great to add this feature.

**Comment by rstoenescu** [comment]
Hi, pondering on this one. Will offer more details (and possibly merge it) next week. Currently I'm overloaded with a new starter kit work. Thanks!

**Comment by alexdee2007** [comment]
Hello Razvan, thanks for your answer.
The uppercase characters is very often used in strict databases, such as banking systems, etc. I missed this opportunity in many frameworks... 
For now i'm using the wrapper component around the QInput to add this feature.
But if you added this small feature, it would be great, not just for me )

Thanks for pondering on this one!

**Comment by rstoenescu** [comment]
Available in future v0.15. Thanks for taking time for a PR!

**Pull request merged**
