### PR TITLE
Removed pathname from URL in readFileSync and changed replaceAll to replace

### PR DESCRIPTION
**Pull request by customautosys**
This was not working in node 14 on Windows. Believe that readFileSync works with the URLs without using pathname - using pathname causes an ENOENT. For replaceAll, there's no need to use it as the regex contains /g, using replace is good enough and works with node 14.

**What kind of change does this PR introduce?** 

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on an Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rstoenescu** [comment]
Hi,

It might work without pathname in Node 14, but it breaks any newer Node.js....

**Comment by customautosys** [comment]
> Hi,
> 
> It might work without pathname in Node 14, but it breaks any newer Node.js....

Dear Razvan,

I just tested on nodes 16, 18 and 20 and in all of them removing the .pathname works.

**Comment by rstoenescu** [comment]
I am unsure of your testing methodology, but `new URL()` creates an Object, not a String, which is required for fs.readFileSync to work...

**Comment by customautosys** [comment]
> I am unsure of your testing methodology, but `new URL()` creates an Object, not a String, which is required for fs.readFileSync to work...

Dear Razvan,

According to the node docs, readFileSync accepts string, Buffer, URL, or integer.

https://nodejs.org/api/fs.html#fsreadfilesyncpath-options

**Comment by rstoenescu** [comment]
Uh, oh. My bad. Confused readFileSync with something else. You are perfectly right.
Sorry for the noise and thanks for contributing!

This will be available in next q/app-vite and q/app-webpack.

**Comment by rstoenescu** [comment]
Need sleeeep :)

**Comment by customautosys** [comment]
> Need sleeeep :)

Many many thanks, get some rest busy man!

**Pull request merged**
