### PR TITLE
Emit `input` event when whithin small breakpoint

### PR DESCRIPTION
**Pull request by BenoitRanque**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/master/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rstoenescu** [comment]
`@input` event is reserved for openedBig.

However since you can specify breakpoints, you can hook into `@left-breakpoint` or `@right-breakpoint`.
http://quasar-framework.org/components/layout.html#Vue-Events

**Comment by BenoitRanque** [comment]
My goal is to detect the panel closing/opening. How can I do that with `@left-breakpoint`?

**Review by rstoenescu — COMMENTED** [review]
The "@input" event needs to reference the openedBig states only, otherwise we bump into troubles.

**Comment by rstoenescu** [comment]
No longer applies as QLayout has been rewritten. You don't need this functionality anymore as each layout part has a v-model now.

**Pull request closed without merging**
