### PR TITLE
Limiting QDate view to only years or only months

### PR DESCRIPTION
**Pull request by MilosPaunovic**
Hi guys, I've created a little feature which limits QDate view to only year or months.
Screenshot 2022-04-07 at 13 57 20
Screenshot 2022-04-07 at 13 56 57

It's based on [https://github.com/quasarframework/quasar/discussions/13101]( https://github.com/quasarframework/quasar/discussions/13101) this request.

If you think this makes sense; i could potentially fix getHeader() to not force `minimal` as I've left it now.

### CODE REVIEW

**Comment by NicoP-S** [comment]
Hi @MilosPaunovic and thanks for the fast implementation. 
i started the discussion. My goal Was it to have a monthpicker where year and month can be selected together like in the codesandbox in the discussion. 

In your Screenshots only month OR year is possible right?

**Comment by MilosPaunovic** [comment]
@NicoP-S Hi, yes, at the moment, there are only year OR month pickers. But, if there is interest in this, I could implement year/month picker, as well.

**Comment by NicoP-S** [comment]
I am defenetly interested in an year +month picker!
Thats why i started the discussion. 

It should be like 
https://vuetifyjs.com/en/components/date-pickers-month/

**Comment by MilosPaunovic** [comment]
Screenshot 2022-04-08 at 10 16 26
@NicoP-S It's gonna need some more tweaking, but it deff could be done. Will report back with the results.

**Pull request closed without merging**
