### PR TITLE
feat(quasar) add webview mode

### PR DESCRIPTION
**Pull request by lucasfernog**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

This PR adds webview mode to Quasar, currently through Rust. Running it is as simple as executing `quasar dev -m webview` and `quasar build -m webview`. I am still testing it on Windows, but on Linux its working as expected, with further tests to be made later today.

This is just a preview, i will polish the webview.open part.

### CODE REVIEW

**Comment by nothingismagick** [comment]
I can confirm that dev works on Mac with literally zero config (other than a properly setup rust environment).

**Comment by lucasfernog** [comment]
I am fixing build command, tomorrow I will push changes to embbed JS files into the binary.

**Comment by lucasfernog** [comment]
Pushed some changes to better handle dev/build modes.

**Comment by nothingismagick** [comment]
Don't forget to add the mode to detection @lucasfernog 

```
$ quasar mode --remove webview
 app:mode Detecting installed modes... +0ms

 Mode PWA........ no
 Mode SSR........ no
 Mode CORDOVA.... no
 Mode ELECTRON... no
```

**Comment by nothingismagick** [comment]
Latest changes enable `quasar dev -m webview` to work as expected on mac, however build fails:
```
error: Package `rust-app v0.1.0 .../src-webview/rust-app)` does not have these features: `prod`
```

**Comment by lucasfernog** [comment]
@nothingismagick Sorry, i introduced a breaking change; did you remove and add the webview mode? Also thanks for the reminder about mode detection.. gonna push it and the build fix now

**Comment by lucasfernog** [comment]
Pushed a new structure, with breaking changes. If someone runs webview mode with an old build, please remove the webview mode and let the Quasar CLI re-adds it.

**Comment by nothingismagick** [comment]
Can confirm, `$ quasar build -m webview` works on MacOS.
Screen Shot 2019-06-22 at 00 13 59

And I may be wrong, but the reaction time in webview is light-years faster than electron or normal web.

**Comment by lucasfernog** [comment]
Closing this because i'm working on another approach (with App Extensions) [here](https://github.com/lucasfernog/quasar/tree/feature/portal) and [here](https://github.com/lucasfernog/quasar-webview)

**Pull request closed without merging**
