### PR TITLE
#2530 allow overriding QSelect options QPopover behavior.

### PR DESCRIPTION
**Pull request by amfine-soft-scheminel**
This PR is about allowing the Options QPopover of the select to be positionned above the QSelect and not over the QSelect.

This PR solve the issue  :
https://github.com/quasarframework/quasar/issues/2530
this help **making Quasar QSelect behavior back to the behavior it has in Quasar v0.16**. 
As the new behavior is considered unpleasant by our customers as it not allow to close the QPopover by click/touch on the QSelect (clicking outside may lead to unwanted focus on other elements).

It introduce a new prop on the QSelect. If this prop is unused, the behavior stay the same as before. So the should be no Impact.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/dev/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by amfine-soft-scheminel** [comment]
Not yet. But I do it now and give a comment back in 10 min.

**Comment by amfine-soft-scheminel** [comment]
[x] Iphone 10  OK
[x] chromium OK
[x] firefox  OK
[x] Edge OK
[x] Firefox Android OK

**Comment by rstoenescu** [comment]
Thx. This will go into v0.17.19. Oddly, I introduced same functionality today for v1.0 :)

**Comment by amfine-soft-scheminel** [comment]
Thx, good luck for the v1.0 :+1:

**Pull request merged**
