### PR TITLE
1. Time selection interface format

### PR DESCRIPTION
**Pull request by wedog**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all Quasar themes
- [x] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/master/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
Time selection interface time format for American habit(MM-DD-YYYY). People in other countries may be usedYYYY-MM-DD.  So add configuration 'localeView'.It is a date when the order of the string. If you are in an American time format, you do not need to pass in a value. if you are a Chinese time format , you can ent 'locale-view="year_month_date_hour_minute"'.

### CODE REVIEW

**Comment by realcarbonneau** [comment]
You can already specify any format you want by using the format prop.  See the two links below.  

I also have a pull request #1357 that will use the browser local and automatically set the time picker 24h setting

http://quasar-framework.org/components/datetime.html

http://quasar-framework.org/components/handling-js-date.html#Format-for-display

**Comment by wedog** [comment]
think you.That's a good suggestion.

**Comment by wedog** [comment]
1. delete the localView props 
2. using the format prop

**Comment by rstoenescu** [comment]
Closing as "nativeOn" is the right way at the moment.

**Pull request closed without merging**
