### PR TITLE
Border slider for inputs

### PR DESCRIPTION
**Pull request by Vaerum**
Added a border-slider to input, textarea, .textfield in pure css. The hover, focus .active border slides from left to right.

Check it out if this feature is helpfull

```
To use just do:
<input class="border-slide">
<span></span>

or

<q-select class="border-slide"></q-select>
<span></span>
```

### CODE REVIEW

**Comment by rstoenescu** [comment]
Hi, thanks for taking time for a PR! This will probably be part of a input field component work. We'll leave this open for the moment, until I figure out best way to integrate your commit. Thanks for your efforts!

**Comment by Vaerum** [comment]
@rstoenescu I have tried to make a new pull request, but it just merge the latest commits. How do I make a clean pull request with a new feature only?

Anyways. I have made a search for the Select with inspiration from your search on data-table.

See if you can use it.

/Rasmus

**Comment by smolinari** [comment]
@Vaerum - in order to create a new PR, create a new branch from dev and add the new work to it. Then commit it and create the PR on the new branch. 

Scott

**Comment by Vaerum** [comment]
Thank you Scott ;)

**Comment by rstoenescu** [comment]
@Vaerum This will get into the next big update to Quasar. But followed a completely different path. Your PR is good though. Thanks for taking time to submit it!

**Pull request closed without merging**
