### PR TITLE
Feature: i18n - add russian and ukrainian translations

### PR DESCRIPTION
**Pull request by alexdee2007**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

i18n - add russian and ukrainian translations

### CODE REVIEW

**Comment by Iworb** [comment]
Yes, good additions, but imo not all should be merged.
table.noResults, table.columns, editor.size7 should stay as is.

**Comment by alexdee2007** [comment]
There are has couple errors in #1219
Also implemented plural handler for sharing with multiple translations

**Comment by rstoenescu** [comment]
Thank you!

**Review by alexdee2007 — COMMENTED** [review]
Ahha, sure... lang was added recently ) missed...

**Comment by alexdee2007** [comment]
>Yes, good additions, but imo not all should be merged.
table.noResults, table.columns, editor.size7 should stay as is.

About table.columns:
https://dic.academic.ru/dic.nsf/econ_dict/21189
I think it's all right here.

About table.noResults and editor.size7  - it's a matter of taste ) Yet in text editors such as MS Word size7 just like here.

Best regards, Alex.

**Comment by Iworb** [comment]
table.columns was right, but new translation is right too. It is matter of taste aswell.
There's no any defaults for size3 translation, I think "Обычный" is goot too, because "Стандартный" do not reset it to default, but set `font-size: normal`.

**Comment by rstoenescu** [comment]
Thank you both. If there is anything that needs fixing please agree on it and I'll merge it. I'm relying on you for this as I don't know Russian :)

**Comment by alexdee2007** [comment]
Yes, of course, Razvan)

**Pull request merged**
