### PR TITLE
Allow field name other than 'value' when using static data

### PR DESCRIPTION
**Pull request by BenoitRanque**
**What kind of change does this PR introduce?** (check at least one)

- [x ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/master/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rstoenescu** [comment]
Thanks!

**Comment by rstoenescu** [comment]
Hey, did you test it? :)
https://github.com/quasarframework/quasar/commit/80250d6f9668c1e15ef2d0066f30eb3926fc91b2

**Comment by BenoitRanque** [comment]
No... No reason it should not work however. Will do the mod on my project
and test there.


Cheers

**Comment by rstoenescu** [comment]
Always test before submitting pls. Had to push a commit to fix the second staticData reference :) See this link: https://github.com/quasarframework/quasar/commit/80250d6f9668c1e15ef2d0066f30eb3926fc91b2

**Comment by BenoitRanque** [comment]
Apologies

By the way, how would I test? Is modifying the file in quasar-framework/src
enough? Do I need to push to dist folder? How?
Sorry about the noob questions....

On Sun, May 28, 2017 at 10:43 AM, Razvan Stoenescu <notifications@github.com

**Pull request merged**
