### PR TITLE
feat(model-toggle): add stopPropagation prop

### PR DESCRIPTION
**Pull request by jesusvilla**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
If I want to place QMenu within QExpansionItem or within a selectable QItem I will need to propagate the parent component event, so I have added this new property: stopPropagation
Look: https://codepen.io/jvillanueva/pen/jOPbzjB

### CODE REVIEW

**Comment by pdanpdan** [comment]
Hello. I think  there is no need for this because you can stop the event at parent level. Just add a `@click.stop` on the QIcon.

**Comment by rstoenescu** [comment]
This is a good idea, but I'd like to see it for both show() and hide().

**Comment by rstoenescu** [comment]
And without any prop. We should do this by default.

**Comment by jesusvilla** [comment]
What you tell me is that by default it should be with stopPropagation?, If so, it would be great, I did it with an additional property so as not to affect in other cases.

**Comment by rstoenescu** [comment]
Yes, let's do it by default.

**Comment by jesusvilla** [comment]
But the possibility of propagating the event should be allowed (i still can't find a case), so just add a default value: true

**Comment by rstoenescu** [comment]
I think that we are talking about completely different things.
If all you care is the "click" event which is bound to the toggle() method, then use Vue's ".prevent" modifier. No need for Quasar to handle that. Will make a commit with what I was referring to.

**Pull request closed without merging**
