### PR TITLE
Link to Quasar Play on App Store

### PR DESCRIPTION
**Pull request by morrislaptop**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [X ] Other, please describe:doc

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/master/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by smolinari** [comment]
When did the iOS play app get done? This should be an announcement for sure. 😄 

Scott

**Comment by morrislaptop** [comment]
I have a spare apple dev account so thought I would throw it up there :)

**Comment by mstaack** [comment]
@morrislaptop currently only one line before needs to be changed to ;)

**Comment by morrislaptop** [comment]
@mstaack isn't there some sort of windows store somewhere? :p thanks for the tip!

**Comment by mstaack** [comment]
@morrislaptop no idea ;) dont use or work with windows :)

**Comment by nothingismagick** [comment]
wow... the version is quite old - @morrislaptop - will you be updating it to 0.15?

**Comment by morrislaptop** [comment]
Nope, not using Quasar. Never heard from @rstoenescu

**Comment by nothingismagick** [comment]
Oh, that is a shame. If you are not interested, then perhaps just close the pull-request. (And maybe consider removing the app from the app-store if you don't wish to continue working with quasar...)

**Comment by nothingismagick** [comment]
Thankyou

**Pull request closed without merging**
