### PR TITLE
feat(create-quasar): bump axios version to v1 (fix: #15161)

### PR DESCRIPTION
**Pull request by Mosaab-Emam**
**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: bump axios version

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on an Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Review by MilosPaunovic — APPROVED** [review]

**Review by yusufkandemir — APPROVED** [review]

**Comment by yusufkandemir** [comment]
Thanks for contributing! Will be available in the next `create-quasar` release.

**Comment by Mosaab-Emam** [comment]
My pleasure.

**Comment by Infinity-Kim** [comment]
Don't want to add package updates to npm?

**Comment by Mosaab-Emam** [comment]
I didn't get you @Infinity-Kim, please clarify

**Comment by Infinity-Kim** [comment]
> I didn't get you @Infinity-Kim, please clarify
Yesterday I launched two new projects

One using yarn create
Second with npm init

When using npm init quasar, axios has version 0.21 (release from 2020). Doesn't that seem like a problem?

**Pull request merged**
