### PR TITLE
Prevent QSelect's filter to propagate to parent QField

### PR DESCRIPTION
**Pull request by pdanpdan**
**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [X] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/master/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [X] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

When we have QField > QSelect[filter], the input from QSearch(filter) is published into QField's input, overriding the select. So in this case QField thought that it's child was the QSearch, not the QSelect.

### CODE REVIEW

**Comment by pdanpdan** [comment]
It's not ok. Need more work.

**Comment by pdanpdan** [comment]
It looks like the first version was the right one

**Comment by pdanpdan** [comment]
Do you know of a way to provide from a functional component? I tried it and it doesn't seem to work.

**Comment by rstoenescu** [comment]
@pdanpdan Do a search on "functional: true" in the codebase. One difference is that you'll be using ".js" extension instead of ".vue".
There's a "but": don't think that the Vue provide API works for functional components. Might be worth a re-check.

**Comment by pdanpdan** [comment]
It looks like it's not implemented, so I would leave it as it is now.

**Pull request merged**
