### PR TITLE
fix(@quasar/app): preFetch to work on TypeScript components #3501

### LINKED ISSUE #3501: [v1] preFetch doesn't work when a component is wrapped in Vue.extend
A component like the one below (used for TypeScript)

```js
export default Vue.extend({
  nane: 'DefaultLoggedInLayout',
  preFetch ({ store, currentRoute, previousRoute, redirect, ssrContext }) {
    console.log('Prefetch')
  }
}
```
Won't have preFetch triggered.

I have a fix for it so will sort a PR.

### PR DESCRIPTION
**Pull request by webnoob**
fix #3501

**What kind of change does this PR introduce?** (check at least one)

- [ x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x ] It's submitted to the `dev` branch and _not_ the `master` branch
- [x ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [x ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/dev/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

I've tested it on my app running typescript and also an electron / SPA app to ensure it doesn't break normal functionality.
Note: My tests were only done by manually changing `.quasar/client-prefetch.js` and not by letting the CLI re-build the file but I don't see any issues with the change (assuming your happy with the coding style of the extra checks)

### CODE REVIEW

**Comment by rstoenescu** [comment]
Isn't it "options" and not "extendOptions" ?

**Comment by rstoenescu** [comment]
And shouldn't `m => m.c && typeof m.c.preFetch === 'function'` be surrounded by paranthesis? Otherwise the OR operation is unclear.

**Comment by webnoob** [comment]
Funny, I had that wrapped in parenthesis but removed on re-format. Whoops. I'll add it bad in.

Re: options. It seems that both would suffice. `extendOptions` looks like it just contains the props used in that component. `options` looks like it includes all the other baked in ones.

**Comment by rstoenescu** [comment]
Yes, let's go with `options`. Also please do a test on SSR.

**Comment by rstoenescu** [comment]
Should do the same trick with server-entry.js too

**Comment by webnoob** [comment]
Ah right, I didn't even see that did anything with preFetch.
Will do that as well.

**Comment by webnoob** [comment]
I had someone to test the changes for me so I went ahead and did them without chatting about it (I thought you could just look at the changes and see if you're happy). Feel free to grab me on discord.

Basically, I've reverted the previous fix and am instead just changing the initial array to contain the correct components.

Tested on SPA and SSR (thanks to @ValRush in #3501 ).

**Comment by webnoob** [comment]
Sorry @rstoenescu Didn't even think of the App instance! 
Will also make a mental note of your optimizations for future commits.

**Comment by rstoenescu** [comment]
Made some adjustmest and merged.

**Comment by rstoenescu** [comment]
Will be available in @quasar/app beta.11

**Pull request merged**
