### PR TITLE
fix(QScrollArea): prevent content re-rendering on scroll or mousemove (fix #16579)

### LINKED ISSUE #16579: Functions inside qscrollarea keeps getting called over and over when scrollbar changes (visibility or movement)
### What happened?

So I'm noticing odd function call behavior inside a qscrollarea.  It seems anytime I mouse over the scroll area the function gets called which is not what happened in v1.  Computed behaves as expected.  And you don't even have to scroll.  Just mouse enter and leave and you'll see the function get hit.  How do I revert back to how v1 behaved or is this some odd vue 3 reactivity interaction I'm not understanding.   It seems to be tied to scroll bar.  If I set it to visible I can mouse over and out all day and it won't trigger b/c the scroll bar isn't fading in and out.  Unfortunately, moving the scroll bar will also trigger the function call.

### What did you expect to happen?

I expected it to not constantly call functions inside qScrollArea.  Quasar v1 does not exhibit this behavior.

### Reproduction URL

https://codepen.io/aroganx/pen/gOqWgBY

### How to reproduce?

Run the codepen and just mouse over in and out of scroll area.  Scrolling in the scroll area will also cause the function to get called repeatedly.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.22621) - win32/x64
NodeJs - 18.17.1

Global packages
  NPM - 9.8.1
  yarn - 1.22.19
  @quasar/cli - 2.2.3
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.12.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-webpack - 3.9.6 -- Quasar Framework App CLI with Webpack
  @quasar/extras - 1.16.6 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.4 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.4
  pinia - Not installed
  vuex - 4.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.22.11 -- Babel compiler core.
  webpack - 5.88.2 -- Packs ECMAScript/CommonJs/AMD modules for the browser. Allows you to split your codebase into multiple bundles, which can be loaded on demand. Supports loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.11.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.9.4 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  @quasar/quasar-app-extension-qcalendar - 4.0.0-beta.16 -- A Quasar App Extension for @quasar/quasar-ui-qcalendar
  @toby.mosque/quasar-app-extension-qdatetimepicker - 2.0.0-rc.3 -- Quasar Date Time Picker Extension
  @quasar/quasar-app-extension-qmarkdown - 2.0.0-beta.10 -- Display inline markdown in your Quasar App

```

### Relevant log output

```Shell
testComputed: 1
testFx: 16
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by thexeos**
**What kind of change does this PR introduce?**

- [X] Bugfix

**Does this PR introduce a breaking change?**

- [X] No

**The PR fulfills these requirements:**

- [X] It's submitted to the `dev` branch (or `v[X]` branch)
- [X] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on an Electron app

**Other information:**

After separating out the thumb rendering logic into a separate component we can isolate the rendering when scroll position is updated or thumb is shown/hidden.

The HTML and CSS output remains unchanged. The functionality remains unchanged. UI tests under ui/dev (ui/playground) all appear to be functioning as expected.

## Before the change

chrome_WAZ7HH9OAi

## After the change

chrome_NNniFDGsQY

This would fix #16579

### CODE REVIEW

**Comment by thexeos** [comment]
I found an edge case where it still triggers re-rendering. So this requires a little more work.

**Comment by thexeos** [comment]
It turns out that Vue behaves slightly differently in dev and prod modes. It seems the effect isolation is more strict in dev and so it was not triggering the re-rendering of scrollable content when `mainStyle` was re-computed after `hover` ref was updated in `@mouseenter` and `@mouseleave` event handlers.

A complete solution is not possible without changing the code flow, as **QScrollArea** render function ultimately depends on `scroll.vertical.thumbHidden` and `scroll.horizontal.thumbHidden` values, which in turn change when showing/hiding the scrollbars in "default" `visible` mode.

Despite not being a complete solution, this change achieves:
- No more pointless re-rendering of content when scrolling [had the largest affect on performance]
- No more pointless re-rendering of content when showing/hiding the scrollbars, **as long as `contentStyle` or `contentActiveStyle` props of **QScrollArea** were not set**

This PR should be ready for merging.

**Comment by rstoenescu** [comment]
Hi,

Huge thanks for contributing! There were merge errors so written this myself using your great sub-component idea.
Perf improvement will be available in Quasar v2.17.0

**Comment by rstoenescu** [comment]
Again, excellent work!

**Pull request closed without merging**
