### PR TITLE
feature: add breakpoint specific col grow and add missing min-height to col auto

### PR DESCRIPTION
**Pull request by pdanpdan**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [X] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/master/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [X] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

col-{breakpoint}-grow specific classes

### CODE REVIEW

**Comment by rstoenescu** [comment]
I believe that the `grow` doesn't quite makes sense to work with xs-, sm- etc prefixes. Not saying this isn't right, but also trying to keep the CSS footprint as low as possible. After the "Design Helpers > CSS flexbox" docs section will be written it will be more clear on what I mean.

**Comment by pdanpdan** [comment]
Maybe I missed some details, but I can see no way to do this:
- 1 .row container with 2 cells inside
- you want them to be full width on <=sm
- you want them to fill the row on > sm, and have independent, not predefined sizes

What I can think of is .row>.col-sm-grow

**Comment by rstoenescu** [comment]
```html
<div class="row">
  <div class="col">...</div> <!-- could use col-6 too -->
  <div class="col">...</div> <!-- could use col-6 too -->
</div>
```
By default rows are now "wrapping content". So you can define col-*-12 to make it spread whole width and next cols will go to next line.

```html
<div class="row">
  <div class="col-xs-12 col-sm-6">...</div> <!-- could use col-6 too -->
  <div class="col-xs-12 col-sm-6">...</div> <!-- could use col-6 too -->
</div>
```

Check path `#/css/grid-rows` on Quasar repo dev server for all it can do. Play with the width of window.

**Comment by pdanpdan** [comment]
This would only create equal or predefined size splits.
For the moment breakpoint specific .col-auto is implemented, leaving .col-grow as an orphan.

**Comment by rstoenescu** [comment]
You could also use:
```
<div class="row">
  <div class="col-xs-12 col-auto">...</div>
  <div class="col-xs-12 col">...</div>
</div>
```
This makes one each child div spread full width on smaller than `xs` devices and on sm+ first div has auto width while the second div will spread full width.

**Comment by rstoenescu** [comment]
Also check "Variable width content" on the Q dev server page I mentioned.

**Comment by pdanpdan** [comment]
Ok, I'll keep it in userland :)

**Comment by rstoenescu** [comment]
Yes, but like I said, you don't really need it...

**Pull request closed without merging**
