### PR TITLE
feat(docs): New "Meet the Team" page

### PR DESCRIPTION
**Pull request by hawkeye64**

### CODE REVIEW

**Comment by nothingismagick** [comment]
Whatever happened with this PR? @rstoenescu ???

**Comment by hawkeye64** [comment]
It's a lost soul :)

**Comment by rstoenescu** [comment]
It's a good start, but not there yet. Will need some individual info from each... will discuss more when v1.0 is closer to final build.

**Comment by hawkeye64** [comment]
:+1:

**Pull request merged**
