### PR TITLE
Add date suffix (1st, 2nd, 3rd) token to formatDate()

### PR DESCRIPTION
**Pull request by dsl101**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [x] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

New token introduced in the date formatter string, so existing applications which use that token will not behave as expected.

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/master/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

Frequently I want to display nicely formatted 'human readable' dates, such as 18ᵗʰ August 2017. This was quite hard to do with the existing date formatter, so I've added a token - `^` which will be replaced by the appropriate 2-character superscript string (using the Unicode superscript character block). So, for example, you can now do:

    const nice = formatDate(new Date(), 'D^ MMM YYYY')  // 18ᵗʰ August 2017 on day of submitting

### CODE REVIEW

**Comment by dsl101** [comment]
BTW - the additions to the demo page probably aren't right - I just wanted a quick way to eyeball what I'd added. But I guess if it's going to be there, it should show more of the `formateDate()` options. And then what about the other helpers... And pretty soon it unravelled so I left it as is :).

**Review by rstoenescu — CHANGES_REQUESTED** [review]
Hi,

Nice PR! Two comments though:

1. Can we make it inline with the other date libraries and use "o" instead of "^". Actually, take a look at this to get what I mean: https://date-fns.org/v1.28.5/docs/format -- notice tokens like "Mo", "Qo" and so on... I think it will be better to get in line with current major date libraries.
2. This will probably get merged (haven't decided yet) after the i18n work is finalized, as it might depend on it. For example for Romanian translation "Mo" should not contain the day endings ("st", "nd", "rd" etc), but this is out of the scope of current PR, so let's just focus on making it work like on point 1.

Thanks for contributing!

**Comment by dsl101** [comment]
Great - I will have a look at that standard - I was originally trying to minimise potential conflict with creating new tokens, hence going for an unusual character. But if there are some standards out there, that's probably better. And I agree about internationalisation. I was trying to think if there was a 'formula' or other options object which could override the default English suffixes but (a) the English 'formula' isn't exactly simple, and (b) I have no idea what other languages use for date suffixes :). Happy to take a look in the context of the i18n stuff when it's ready.

**Comment by rstoenescu** [comment]
Let's leave i18n out of this one for now and simply focus on adding those tokens. We'll deal with i18n later. Thanks again for taking care of this!

**Comment by dsl101** [comment]
OK, I've added the 'Do' token, and also allowed the user to pass in a custom function to return a date suffix, so it could be used like this:

    methods: {
      fmt (date, format) {
        return formatDate(new Date(date), format, {dateSuffix: this.customSuffix})
      },
      customSuffix (d) {
        return d + '°'
      }
    }

The function expects a date (1-31) and should return the number _and_ suffix. The default is to provide the regular 1st, 2nd, 3rd, etc.

Did you want me to add the 'Mo', 'Qo' tokens as well? To be honest, I'm not sure where they'd be used but I guess for completeness they should be there?

**Comment by spectrolite** [comment]
In french you would only need a suffix for the 1st day of the month (1er -for premier), all other days are without suffix.
The same rule is true in italian, and the suffix is the degree symbol as in : 1° maggio.

Please also note that months are never capitalised in dates (neither in fr nor in it), although they usually get Capitalized e.g. if they’re on their own on top of a calendar’s month view, but that’s more of an i18n issue.

**Comment by dsl101** [comment]
I _think_ @rstoenescu decided to do this in a different way but I honestly can't remember now. But I think you can do everything you described by passing in a custom function to the code I original posted.

**Comment by rstoenescu** [comment]
Hi,

Thanks for your work! Added Do and Qo, but in a slightly different way. Available in edge and future v0.14.7.

**Pull request closed without merging**
