### PR TITLE
fix(lang): improve some zh-TW translations

### PR DESCRIPTION
**Pull request by brownsugar**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by hawkeye64** [comment]
Thank you for your contribution. I was a little unsure of the "pagination" in the first file, but I see it got resolved in the second file. I am using Google Translate. The only other issue I see is "recordsPerPage" where `每頁列數` translates to `Number of columns per page`. Is there something else that can be used in place of "columns" or is that just how Google Translate is translating it?

**Comment by brownsugar** [comment]
@hawkeye64 
Hi, as I know, Google Translate uses grammars of Simplified Chinese (zh-CN) for all Chinese related translations, but there is some difference between Traditional (zh-TW) and Simplified Chinese for the words "列" and "欄":

1. "列" (or "行") is "row" in TC, but it's "column" in SC.
2. "欄" is "column" in TC, but it's "row" in SC.

So according to the grammar in Taiwan, "recordsPerPage" means rows per page, which is translated to "每頁列數".
Also I've checked Google's official TC translation in Search Console:
Snipaste_20210904001130297

Which matches the current submitted translations.

**Comment by hawkeye64** [comment]
Sounds good to me. Good job explaining, thanks.

**Comment by hawkeye64** [comment]
Thanks for your contribution!

**Pull request merged**
