### PR TITLE
fix(Notify plugin): actions CSS - sane default color (black)

### PR DESCRIPTION
**Pull request by euphemism**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: Changing a default CSS color

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
The default text color for the notification's actions is an odd purple. I figure having the default be black makes more sense.

### CODE REVIEW

**Comment by rstoenescu** [comment]
Hi,

Thank you for contributing!
The current color is per Material guidelines though...

snackbar

**Comment by euphemism** [comment]
Hi Razvan, thank you for the prompt response. I have not been able to find anything on [material.io](https://material.io/) that actually dictates that the default color of the action is supposed to be this particular purple. I see things like the following:

* To distinguish the action from the text label, text buttons should display colored text.
* The text label shouldn’t share the same color as the text button.
* Don’t use a filled or elevated button in a snackbar, as it draws too much attention.

The specifications site is using a range of purples as the primary color, but there is nothing to indicate that this is expected to be the default. Looking at the snackbar's spec for color, it only specifies the color for the bar itself, not the action button: 
material_design_snackbar_color

**Comment by rstoenescu** [comment]
But regardless, pure black is not a good color for it...

notify-change

**Comment by euphemism** [comment]
I would agree with that. For some reason I was thinking of a dialog with a white background. I noticed the purple on a notification that I had changed the default background color of, and it didn't occur to me when I made this quick change that Quasar's snackbars are a dark grey by default. If I change this to a lighter grey or white would that be acceptable?

**Comment by euphemism** [comment]
It might make sense to have this default to the primary color.

**Pull request closed without merging**
