### PR TITLE
fix(docs, componenmts,...): Fix spelling errors

### PR DESCRIPTION
**Pull request by ejez**
Fix spelling errors in docs and code.

### CODE REVIEW

**Comment by ejez** [comment]
A spell checking tool installed in the editor will be very useful to avoid spelling errors.

for example: [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker&ssr=false#overview) for vscode

(would be nice to include it here: https://quasar.dev/start/vs-code-configuration#Recommended-additional-VS-Code-extensions-and-settings-updates )

**Comment by hawkeye64** [comment]
Wow! Nice job catching all of those. The one thing I am not sure of is the `fortawesome` vs `fontawesome` (https://fortawesome.com/). Owned by the same guy, but you purchase through fortawesome, I believe, and Fontawesome is just one of their free sets.

**Comment by ejez** [comment]
did not know that, thought it was a typing error :)
will submit a new commit to bring it back, thanks

**Comment by rstoenescu** [comment]
Thanks for contributing! Really appreciate you catching all these.

**Comment by hawkeye64** [comment]
@ejez Yeah, was amazing there were so many that others had missed. Again, many thanks.

**Comment by ejez** [comment]
Thanks to you all for the hard work in this great framework.

**Pull request merged**
