### PR TITLE
Update table.md - fix typo

### PR DESCRIPTION
**Pull request by kostyfisik**
Fix typo

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [X] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch (or `v[X]` branch)
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by pdanpdan** [comment]
Why? It's about QTr

**Comment by kostyfisik** [comment]
In the related code under the warning `:key` is added on `QTh` inside `QTr`, not on `QTr` directly as it is written in the current version of documentation. 
```html
      ...

      <template v-slot:header="props">
        <q-tr :props="props">
          <q-th auto-width />
          <q-th
            v-for="col in props.cols"
            :key="col.name"
            :props="props"
          >
            {{ col.label }}
          </q-th>
        </q-tr>
      </template>
      ...
```

**Comment by kostyfisik** [comment]
OK, may be I got it. Should it be
```
::: warning
Add unique (distinct) `key` on element of QTr from `header` slot if you generate more than one QTr in `body` slot from a row in input data.
:::
```

**Comment by kostyfisik** [comment]
Urgh... Sorry. I was looking for a `key` in `<q-tr>` and missed that it is both in `header` and `body` slots in `<q-th>` and `<q-td>` respectively. So current warning is probably OK, however, it is misleading....

**Pull request closed without merging**
