### PR TITLE
Add Example - debounce / throttle on methods.

### PR DESCRIPTION
**Pull request by webnoob**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rstoenescu** [comment]
This throttled/debounces for ALL instances of that respective component.
Should use a beforeMount hook to initialize those methods instead.

**Comment by webnoob** [comment]
Like this?

```js
methods: {
  myfunction () {
    // Run some code.
  }
},

bedforeMount () {
  this.myFunction = debounce(this.myFunction, 500)
}
```

Also, could you explain:

> This throttled/debounces for ALL instances of that respective component.

Do you mean the timeout will be shared among all rendered versions of that component so if you have 6 on the page, you can only run the function once between the all the components every XXX ms?

**Comment by rstoenescu** [comment]
@webnoob 

Why also defining it in methods? Just this will suffice:

```
beforeMount () {
  this.myFunction = debounce(this.myFunction, 500)
}
```

The Vue component definition is exactly what gets instantianted. So if you define a method with the result of the debounce function (methods: { doSmthng: debounce(...) }) you're essentially telling the instantiation Object to have that method pointing to SAME function. So it gets shared by all rendered instances.
When you instantiate a component, the instantiating object is already created (it doesn't gets evaluated again). Does this makes sense to you?

**Comment by webnoob** [comment]
Your explanation makes perfect sense, thanks.

I also put it in methods as I personally find it tidier - the method is still defined in methods (where you would expect it) but if you want it debounced, you just add a line in `beforeMount`.

If I understand you correctly if I didn't put it in methods, I'd need:

```js
beforeMount () {
  this.myFunction = debounce(function () {
    // Do my code here.
  }, 500)
}
```

Which way would you like it documented? Given the confusion I've clearly had with this, I think it's imperative we at least document it somehow.

**Comment by rstoenescu** [comment]
Bulletproof approach:

```
methods: {
  myMethod () { .... }
},

created () {
  this.myMethod = debounce(this.myMethod, 500)
}
```

I just realized there are devs that might not know how to use arrow functions yet.. long story short, document like above.

**Comment by webnoob** [comment]
Ok, will sort it now.

**Comment by webnoob** [comment]
I've also added a warning in there because examples I've seen online demonstrate doing it the way I did initially but without the warning you gave me.

p.s Perhaps we should be educating people about useful things like arrow functions etc in a tips doc.

**Comment by rstoenescu** [comment]
Thanks for your time on this one!

**Pull request merged**
