### PR TITLE
QFileUpload component created.

### PR DESCRIPTION
**Pull request by murbanowicz**
QFileUpload component.

It is working. Uploading files and images.
It is basically the button to choose files. When you choose files, modal with files/images list opens.
You can see images thumbnails if `imageUpload` is set `true` and delete images from the list.
You can see the list with files names and you can choose and delete.

I did not style modal (almost) at all as I just can't get a good idea how it should look like, 
but for @rstoenescu or other guys (maybe @smolinari or someone else) it should not be an issue.

Hope you like it!

Still TODO:
Show upload errors.
Show upload progress.
Style files/images list modal.

### CODE REVIEW

**Comment by rstoenescu** [comment]
Will take a look and merge it in the following days. Thanks for your efforts!

**Comment by rstoenescu** [comment]
Please hold on there. This will soon get into Quasar.

**Comment by murbanowicz** [comment]
What you mean? You will use my PR or scrap it?

18 gru 2016 16:38 "Razvan Stoenescu" <notifications@github.com> napisał(a):

Please hold on there. This will soon get into Quasar.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/quasarframework/quasar/pull/250#issuecomment-267831289>,
or mute the thread

**Comment by rstoenescu** [comment]
Use your PR, just had no time yet to look over it and test. Thought I'd drop you a message to let you know that your work will get in.

**Comment by rstoenescu** [comment]
Thanks for your hard work!

**Comment by murbanowicz** [comment]
@rstoenescu  did you really used it? I see lot of changes in actual Uploader ?

**Comment by rstoenescu** [comment]
Got inspired by it and used bits of code.

**Pull request merged**
