### PR TITLE
Quasar website GUI update

### PR DESCRIPTION
**Pull request by IlCallo**
**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [x] Feature
- [x] Documentation
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**

Some important notes:
- we may want to check [this PR](https://github.com/quasarframework/quasar/pull/14153/files) out to see if somethings could be useful to port into this PR
- templates of new additions are in plain HTML, since we don't know PUG and we find the usage of PUG to be an entry barrier for new contributions. Same goes for SASS syntax: we tried to not touch where it is used, but it would be best if we switch to the widely used SCSS syntax instead
- the "docs-gui-update" issue template should be tested, but the label has already been added
- sponsors list is outdated, we need to update it and use the list into `src/assets/sponsors` as the single source of truth
- sponsors logos should be uploaded to the CDN
- since we added the dark mode, we need both light and dark mode for each sponsor logo
- images used into the new Landing page should probably be uploaded into the CDN
- drawer banners are commented out, enable them to check out the GUI, but disable them again when pushing the preview
- VueMastery affiliate links are disabled as we wait for feedback by them about some technical details, enable them to check out the GUI, but disable them again when pushing the preview (they're not tracking our affiliate code right now)
- ~the roadmap page now uses the root ROADMAP so it's automatically in sync with each new deploy~ this worked fine with webpack, but caused problems with Vite, so we replaced roadmap page with a link to the actual roadmap on GH
- we should publish the new docs into `new.quasar.dev` subdomain and add a link into the current docs to highlight them

Since we merged a couple of times upstream/dev on this branch after the Vite conversion, since rebase became increasingly difficult, I'd suggest to do a squash before merging, when the time comes

When everything is clear, please check out known issues [here](https://github.com/dreamonkey/quasar/issues)
[Critical](https://github.com/dreamonkey/quasar/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aseverity-0-critical) and [important](https://github.com/dreamonkey/quasar/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aseverity-1-important) ones must be solved before releasing the preview

We should focus on technical issues and UX problems in the preview phase.
We'll collect other feedback into the incoming survey and adapt the GUI accordingly, if something still feels wrong about the new GUI after a month or so

### CODE REVIEW

**Comment by IlCallo** [comment]
Apparently Vite doesn't really like the `ROADMAP` route we're adding, probably because it's outside docs project, I just noticed it while trying to build the docs.
I'd remove the page untirely and just redirect to `https://roadmap.quasar.dev` when selecting that page from the navigation menu

**Comment by Saeid-Za** [comment]
Hello, A quick question, as stated in the description of this pull-request, there would be no change on old `pug` and `sass` files, would this be held true after this first release or would quasar team later come back and refactor the old codebase?
I'd be happy to help on migrating.

**Comment by IlCallo** [comment]
Thanks for the offer :)
We haven't discussed that yet, but we'll do as soon as we find the time to review this PR and release the new website

**Comment by yusufkandemir** [comment]
Closing as this has been merged and released. 
https://github.com/quasarframework/quasar/commit/a54ebcbc21727e8d015ea3361a32dd2091b8894a
https://github.com/quasarframework/quasar/discussions/15636

**Pull request closed without merging**
