### PR TITLE
fix: fix sass depration warnings

### PR DESCRIPTION
**Pull request by sschneider-ihre-pvs**
Long time deprecation warnings fixed

### CODE REVIEW

**Comment by ghiscoding** [comment]
I assume that would fix #14362 and #11683 but I wonder what the core team member will say this time since his last comment (in the first issue) was to pin the SASS version to `1.32.13` (before all these SASS warnings came in to play). It would be awesome if we could finally upgrade to latest SASS 🚀

**Comment by wt0m** [comment]
Great news! Will we be able to finally upgrade to the latest SASS?

**Comment by staszek998** [comment]
Is there a way to somehow "bump" this PR, so it'll be merged into production earlier than later? 😉

**Comment by rstoenescu** [comment]
Hi,

Thanks for contributing! We went with another approach, but regardless, closing this as everyone can now use latest Sass.

**Pull request closed without merging**
