### PR TITLE
feat(app): update webpack-dev-server to v4.0.0-rc.0

### PR DESCRIPTION
**Pull request by hawkeye64**
The only issue I saw is handling for this which may need extra tweaking:
- host and port options can't be null or empty string
https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-rc.0

### CODE REVIEW

**Comment by LeoniePhiline** [comment]
Yes! This update is dearly needed.

Right now, neither the old nor the new option validate successfully:

Old:
```js
  devServer: {
    sockPort: 443,
  },
```
(This fails, because `sockPort` no longer validates.)

New:
```js
  devServer: {
    webSocketURL: {
      port: 443,
    },
  },
```
(This fails, because `webSocketURL` does not validate in webpack-dev-server@4-beta, but that is fixed in rc.0.)

See also: https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md

**Comment by LeoniePhiline** [comment]
@hawkeye64 Why did you close the PR?

**Comment by therealcoder1337** [comment]
@LeoniePhiline i guess because more work is needed, as i outlined in https://github.com/quasarframework/quasar/issues/10083#issuecomment-893016702 and https://github.com/quasarframework/quasar/issues/10083#issuecomment-893640785
simply bumping the dependency will not help, because of needed migration steps.

**Comment by LeoniePhiline** [comment]
Ah I see. Thank you!

**Pull request closed without merging**
