### PR TITLE
fix (docs) : Correct the Pinia usage in preFetch

### PR DESCRIPTION
**Pull request by YALCINCAN**
**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [ ] Feature
- [x] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [ ] No

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch (or `v[X]` branch)
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rstoenescu** [comment]
Hi,

You do not need the Pinia instance (`store`) to use any of the stores.

**Comment by TobyMosque** [comment]
https://pinia.vuejs.org/ssr/#using-the-store-outside-of-setup
@rstoenescu that is needed to avoid hidratation issues.
> // ✅ This will work make sure the correct store is used for the
  // current running app
  const main = useMainStore(pinia)

**Comment by rstoenescu** [comment]
@TobyMosque You're right on this one, but:
@TobyMosque @YALCINCAN We should be more clear on this distinction in docs. SSR vs non-SSR. SSR is just one of the Quasar modes (+ preFetch makes sense for non-SSR too) and we shouldn't advertise for useless complexity when it's not the case. So please, can you adapt the PR to this pls?

**Comment by TobyMosque** [comment]
yes, we would mention that is required only to SSR apps.
another point, beside the preFetch, other wrappers are affected too (boot, router)

**Comment by YALCINCAN** [comment]
@rstoenescu @TobyMosque 
sorry i had to open pr again because i deleted the fork
new pr link
https://github.com/quasarframework/quasar/pull/13117
  If there is something you want me to change, you can let me know.

i now close this pr okey ?

**Pull request closed without merging**
