### PR TITLE
Fix for popover.

### PR DESCRIPTION
**Pull request by hazzo**
Temporary fix to avoid popover losing target anchor. The height of the container has a max so elements inside will scroll if they are superior to 50vh.

### CODE REVIEW

**Comment by rstoenescu** [comment]
Thanks for this. Don't quite like the word "temporary". Usually "temporary" becomes permanent from my own experience :))

**Comment by hazzo** [comment]
My pleasure! You are right. Hahaha. Keep on with the good job.
I was going to try and create a directive for ripple effect for material template button but I already saw that you got it implemented for 0.14.
Waiting anxiously!

**Comment by rstoenescu** [comment]
Yep. v0.14 is gonna be a big thing.
I got an idea for a permanent fix on the popover and pushed it to edge. Can you test it out and tell me if it meets your use case? Just want a confirmation. Thx!

**Comment by hazzo** [comment]
Cool! Yeah no problem as soon as I get near my computer I'll tests it. ;)

**Comment by hazzo** [comment]
Razvan sorry for the wait. I can't seem to test it because I don't know what I am doing wrong but the fork from your framework stopped working. I also downloaded the zip from dev branch and then npm install and webpack keeps failing. 
If I can test it I'll let you know. Sure your fix works great ;)
If you have any clue of what can cause my problem it will be of great help.
The compilant gives me error of es6-promise don't know why.

**Comment by rstoenescu** [comment]
Try deleting node_modules and npm installing again.

**Comment by rstoenescu** [comment]
`es6-promise` was requested because of a test I made. Forgot to remove it. Try now with latest edge. Thanks.

**Comment by hazzo** [comment]
Razvan don't know what is happening. Updated to Node 6.10.0 and npm 4.3.0 and still getting errors. Paste it here.

```
> node build/script.dev.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\wamp64\www\quasar-edge-master\build\script.dev.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Guido\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.10.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! quasar-framework@0.13.2 dev: `node build/script.dev.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the quasar-framework@0.13.2 dev script 'node build/script.dev.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the quasar-framework package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/script.dev.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs quasar-framework
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls quasar-framework
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Guido\AppData\Roaming\npm-cache\_logs\2017-03-09T08_38_10_231Z-debug.log


```

**Comment by smolinari** [comment]
Hey @hazzo, 

Is this still a problem? If yes...

What were you trying to do, when you got the error? I've done some testing, but can't reproduce the error. Could you list the steps you are taking please?

Scott

**Comment by hazzo** [comment]
Hi @smolinari. Building the Quasar repo it's not more an issue thanks!

**Comment by smolinari** [comment]
Ah. Ok! Great!

Scott

**Pull request merged**
