### PR TITLE
docs: update broken links in "Configuring BEX" page

### PR DESCRIPTION
**Pull request by staszek998**
Some of the external links were resolving to 404. I've located their current location using the Web Archive and updated their target URLs.

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [ ] Feature
- [X] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [X] No

**The PR fulfills these requirements:**

- [X] It's submitted to the `dev` branch (or `v[X]` branch)
- [ ] [N/A] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] [N/A] It's been tested on a Cordova (iOS, Android) app
- [ ] [N/A] It's been tested on an Electron app
- [ ] [N/A] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] [N/A] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

### CODE REVIEW

**Review by yusufkandemir — CHANGES_REQUESTED** [review]
Hi, nice catch. Thanks for contributing.
Please apply the same changes to quasar-cli-webpack one too: https://github.com/quasarframework/quasar/blob/dev/docs/src/pages/quasar-cli-webpack/developing-browser-extensions/configuring-bex.md

**Comment by rstoenescu** [comment]
Committed the same changes to the webpack page

**Comment by staszek998** [comment]
Thanks, @rstoenescu! 🙌🏻

**Comment by rstoenescu** [comment]
No, thank YOU for contributing!

**Pull request merged**
