### PR TITLE
fix(app): Electron - missing icons folder in build (#11087)

### LINKED ISSUE #11087: Electron - missing icons folder in build
**Describe the bug**
When `quasar build -m electron` is issued, the `src-electron/icons` folder is not copied to the `dist/electron/unpackaged` folder and therefore will not be packaged into the final electron build.

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**
1. run `quasar build -m electron`
2. go to the `dist/electron/unpackaged` folder
3. you will see it's missing the `icons` folder

**Expected behavior**
You'd expect the icons folder to be copied over

**Screenshots**
image

I have verified this for both Linux and Windows, but have not for Mac (but, assume it's the same)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
 Build mode........ electron
 Pkg quasar........ v2.1.9
 Pkg @quasar/app... v3.1.5

Quasar mode:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [x] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [ ] SSR
  - [ ] PWA
  - [x] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: windows 11/ubuntu 20.04.3
Node: 14.18.1
NPM: 6.14.15
Yarn: 1.22.15
Browsers: 
iOS:
Android:
Electron: 
    "electron": "^15.3.0",
    "electron-builder": "^22.4.0",
    "electron-packager": "^15.2.0",

**Additional context**
I tried to find the code in `@quasar/app` that should do the copying but have not located it yet. I did set a breakpoint in vs code to stop the build. I manually copied the icons folder to unpackaged. I then let the build continue. When running the output on Ubuntu, the icon now shows up for the running app. On windows, the executable and setup both have embedded icons, and running the app shows the icon on the dock bar.

Also, for the icons to work, I added the following code in `electron-main.js` (note: this also works for `dev`):

```js
const iconPath = path.resolve(__dirname, 'icons',
  os.platform === 'win32' ? 'icon.ico'
    : os.platform === 'darwin' ? 'icon.icns'
      : 'linux-512x512.png'
)

function createWindow () {
  /**
   * Initial window options
   */
  mainWindow = new BrowserWindow({
    icon: iconPath, // <-- here
    width: 1000,
    height: 600,
    useContentSize: true,
    webPreferences: {
      contextIsolation: true,
      // More info: /quasar-cli/developing-electron-apps/electron-preload-script
      preload: path.resolve(__dirname, process.env.QUASAR_ELECTRON_PRELOAD)
    }
  })
```

If I can figure this out, I will create a PR.

### PR DESCRIPTION
**Pull request by hawkeye64**
Fixes #11087

### CODE REVIEW

**Review by rstoenescu — DISMISSED** [review]
Not ok.

1. If there would be something to copy then it should be hooked into CopyWebpackPlugin in create-chain.js.
2. Is it really always needed? electron-builder embeds the icons automatically into the executable (but can't remember what it does on Linux);
3. Is this related to building on Linux? Is there something we can do to alleviate the Linux icons problem? Then add it to the electron template.
4. Please test behavior with and without the changes for electron-packager and electron-builder.

**Comment by hawkeye64** [comment]
> 1. If there would be something to copy then it should be hooked into CopyWebpackPlugin in create-chain.js.

Done. Using CopyWebpackPlugin to copy the icons.

> 2. Is it really always needed? electron-builder embeds the icons automatically into the executable (but can't remember what it does on Linux);

You are referring to this code:

```js
      cfg.electron = merge({
        packager: {
          asar: true,
          icon: appPaths.resolve.electron('icons/icon'), // <-- here
          overwrite: true
        },
        builder: {
          appId: 'quasar-app',
          icon: appPaths.resolve.electron('icons/icon'), // <-- here
          productName: this.pkg.productName || this.pkg.name || 'Quasar App',
          directories: {
            buildResources: appPaths.resolve.electron('')
          }
        }
```
This does not work with Ubuntu 20.04.3 or Windows (11). Here, I even tried being more specific by adding the file extension.

> 3. Is this related to building on Linux? Is there something we can do to alleviate the Linux icons problem? Then add it to the electron template.

This is related to building with both Linux (Ubuntu) and Windows (11). Given enough time, I can set up our Mac for development and also test that. However, if the previous code no longer works as expected, this works 100% for Linux and Windows (and I assume Mac).

> 4. Please test behavior with and without the changes for electron-packager and electron-builder.

Tested both `builder` and `packager` with both Linux and Windows. **All 4 variations are working with this fix.**

Here is some more information after further research:

**Builder:**
There is no root-level `icon` in the [commonConfiguration](https://www.electron.build/configuration/configuration). This is defined at the platform level; [linuxConfirguration](https://www.electron.build/configuration/linux),  [macConfiguration](https://www.electron.build/configuration/mac), and [windowsConfiguration](https://www.electron.build/configuration/win).

Also, there's this note:

> Please note — build resources is not packed into the app. If you need to use some files, e.g. as tray icon, please include required files explicitly: "files": ["**/*", "build/icon.*"]

This implies that the icon used currently is for the file output (exe, setup, etc) and not specifically the tray icon.

Based on this information I tried this:

```js
        builder: {
          appId: 'quasar-app',
          linux: {
            icon: appPaths.resolve.electron('icons/linux-512x512.png')
          },
          win: {
            icon: appPaths.resolve.electron('icons/icon.ico')
          },
          mac: {
            icon: appPaths.resolve.electron('icons/icon.icns')
          },
          // icon: appPaths.resolve.electron('icons/icon'),
          productName: this.pkg.productName || this.pkg.name || 'Quasar App',
          directories: {
            buildResources: appPaths.resolve.electron(''),
            files: ['icons/icon.', 'icons/linux-512x512.png']
          }
        }
```

Which did not work.

**Packager:**
Packager has a root-level `icon` in its configuration. For macOS the file must be `.icns`, for windows it must be `.ico`. There is no support for adding an icon to Linux and BrowserWindow must be used to accomplish this.

https://electron.github.io/electron-packager/main/interfaces/electronpackager.options.html#icon

> If the file extension is omitted, it is auto-completed to the correct extension based on the platform, including when `platform: 'all'` is in effect.

> Linux: this option is not supported, as the dock/window list icon is set via the icon option in the BrowserWindow constructor. Please note that you need to use a PNG, and not the macOS or Windows icon formats, in order for it to show up in the dock/window list. Setting the icon in the file manager is not currently supported.

**Comment by hawkeye64** [comment]
I don't know how to get rid of the "changes requested" flag. :(

**Comment by hawkeye64** [comment]
This fix should get rid of this PR: #10142

**Comment by hawkeye64** [comment]
Also, if you create a clean Electron app under Ubuntu, then `process` is missing important values, like `process.platform` and `process.type` (the latter used by VueJs Dev Tools).

```
console.log(process)

> Output

process: {
  nextTick: [Function (anonymous)],
  title: 'browser',
  browser: true,
  env: {},
  argv: [],
  version: '',
  versions: {},
  on: [Function: noop],
  addListener: [Function: noop],
  once: [Function: noop],
  off: [Function: noop],
  removeListener: [Function: noop],
  removeAllListeners: [Function: noop],
  emit: [Function: noop],
  prependListener: [Function: noop],
  prependOnceListener: [Function: noop],
  listeners: [Function (anonymous)],
  binding: [Function (anonymous)],
  cwd: [Function (anonymous)],
  chdir: [Function (anonymous)],
  umask: [Function (anonymous)]
}
```

**Comment by hawkeye64** [comment]
One last thing. This is what happens when you build under Ubuntu 20.04.3 using "builder"

The bottom vscode is where the build occurred. The top vscode is showing an issue with `@quasar/app`. The File Explorer is showing the icons are there, but in the app code, it's not using an extension, so they are unresolved.

image

When I comment out those two lines in `@quasar/app` then the appImage build works.

image

**Comment by rstoenescu** [comment]
Merged and pushed another commit on top of this to add to CopyWebpackPlugin from the main electron build config.

**Pull request merged**
