### PR TITLE
IE related fixes

### PR DESCRIPTION
**Pull request by pdanpdan**
Can you please take a look on this fixes for QBtn in IE/Edge.
The buttons as they are now are broken.
I need some more eyes to check if this doesn't break something else.

### CODE REVIEW

**Comment by pdanpdan** [comment]
Not good yet, need some more work.

**Comment by rstoenescu** [comment]
Ah, dammit. Wanted to take care of this, but seems like you did a pull and this PR now contains a lot of extra commits of my own.

**Comment by pdanpdan** [comment]
Sorry, I just found a corner case where it was not working - multiline text button.
I'll try some more fixes and come back.

**Comment by rstoenescu** [comment]
Thank you so much for your hard work!

**Pull request closed without merging**
