### PR TITLE
Fix language formats

### PR DESCRIPTION
**Pull request by hugetiny**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [x] Documentation
- [x] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:
**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [x] It's been tested on an Electron app
- [ ] It's been tested on a Tauri app
- [x] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
Navigator's language info should not be lowercased, cause a lot of repo like i18n , Electron language detector and browser navigator itself outputs no-lowercased language format like 'en-US','zh-TW','zh-CN'

### CODE REVIEW

**Comment by hugetiny** [comment]
Navigator's language info should not be lowercased, cause a lot of repos like i18n, Electron language detector and browser navigator itself outputs no-lowercased language format like 'en-US','zh-TW','zh-CN'

**Comment by rstoenescu** [comment]
Hi,

I value this PR, but it introduces a serious breaking change, so cannot merge it for Quasar 1.x unfortunately.. Will put this on the 2.x queue. Is that ok for you?

**Comment by hugetiny** [comment]
@rstoenescu Sure~

**Comment by rstoenescu** [comment]
Thanks for your work on it!

**Comment by rstoenescu** [comment]
Will be available in Quasar v2.

**Pull request merged**
