### PR TITLE
Update export-file.js

### PR DESCRIPTION
**Pull request by scg32**
Proposal
In my project where DOM is complex and quasar is as additional library UMD ,function not working correctly ,above solution should fix issue with created link to download ,optional additional parameter is  'id' parent element

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rstoenescu** [comment]
Hi,

Thanks for contributing.
Can you detail more of the problem, please? I fail to understand why this would be needed. A codepen would be wonderful.

Thanks.

**Comment by scg32** [comment]
Hi,
Thank for your answer.
Prepare something on codepen will be painful:) for example in that project what I mentioned we are using html with php jquery etc... and additional we sometimes build component with quasar umd ,but always this  component is wrapped  in  parent or parents so is very nested .I am try using it like Quasar.exportFile but link which is created is not accessible from this context,I want use it to export data from q-table component ,so this is a reason my proposal
I hope so now is more clarify

**Comment by rstoenescu** [comment]
I still don't understand why you need these changes.
It doesn't matter from where this method is called. When called (not a second before or after) it temporarily adds a node in document's body tag, simulates a click on it, then removes it immediately (with no delay between these actions).

**Comment by scg32** [comment]
> I still don't understand why you need these changes.
> It doesn't matter from where this method is called. When called (not a second before or after) it temporarily adds a node in document's body tag, simulates a click on it, then removes it immediately (with no delay between these actions).

yes I agreed with that,the normal project will be working fine , but this is specific environment and doesn't works,so those changes, where you can send as param (tag id) will be helpful in my opinion

**Comment by rstoenescu** [comment]
Well, without actually **explaining the specific environment** I cannot agree with this PR. Without the necessary explanations it's just bloatware from our perspective. Everyone enjoys a non-bloated framework, but if we keep on extending it without solid reasons then it's gonna end up as a trash product.

Please provide the logical explanation why this should be in the framework for everyone to use or feel free to write the adjusted method in your own app then use it.

**Pull request closed without merging**
