### PR TITLE
feat(VirtualScroll): improve scroll update #9329

### PR DESCRIPTION
**Pull request by pdanpdan**
#9329

### CODE REVIEW

**Comment by rstoenescu** [comment]
data-table-part6-virt-loading --> loops forever

**Comment by pdanpdan** [comment]
Yes, I'm working on this

**Comment by rstoenescu** [comment]
Please mark the PR as draft while working on it.

**Comment by rstoenescu** [comment]
Any update?

**Comment by pdanpdan** [comment]
No. It depends on another pr, so it's stuck.

**Comment by rstoenescu** [comment]
Un-stuck it pls.

**Comment by pdanpdan** [comment]
I need a way to detect if the last key pressed before the scroll is a home/end
Else it does not go all the way

**Pull request closed without merging**
