### PR TITLE
clarify(docs): #3769 #3809 #2734 #2728 #2112 #2106

### PR DESCRIPTION
**Pull request by mesqueeb**
clarification for:
#3769 #3809 #2734 #2728 #2112 #2106

All these issues asked exactly the same 😅

### CODE REVIEW

**Comment by mesqueeb** [comment]
PS: I would advice to also write a warning inside the Dialog API under **"maximized"**, but I forgot how to suggest an edit for those API sections.

**Comment by lucasfernog** [comment]
"position"? did you maen

> PS: I would advice to also write a warning inside the Dialog API under **"maximized"**, but I forgot how to suggest an edit for those API sections.

[Here](https://github.com/quasarframework/quasar/blob/dev/ui/src/components/dialog/QDialog.json)

**Comment by mesqueeb** [comment]
@lucasfernog Thanks! 
I added an extra commit to this PR now.

**Comment by nothingismagick** [comment]
Really nice. Thanks!!!

**Pull request merged**
