### PR TITLE
fix(ui): Remove warning log during "factory-failed" emit (fix: #15395)

### LINKED ISSUE #15395: Bug QUploader when emit "factory-failed"
### What happened?

Factory failed is defined as `'factory-failed'` but emitted as `'factoryFailed`.

warning:
```
[Vue warn]: Component emitted event "factoryFailed" but it is neither declared in the emits option nor as an "onFactoryFailed" prop.
```

image

image

### What did you expect to happen?

Not having warning.

### Reproduction URL

https://codesandbox.io/s/vibrant-jang-5876uj?file=/src/pages/Index.vue

### How to reproduce?

Make an upload and check the console

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

_No response_

### Relevant log output

```Shell
[Vue warn]: Component emitted event "factoryFailed" but it is neither declared in the emits option nor as an "onFactoryFailed" prop.
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amal-qb**
**What kind of change does this PR introduce?** 

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] It's been tested on a Cordova (iOS, Android) app
- [x] It's been tested on an Electron app
- [x] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**
Fixes #15395

### CODE REVIEW

**Comment by amal-qb** [comment]
@yusufkandemir Can you please check why one of the tests fail?

**Comment by yusufkandemir** [comment]
It's probably a flaky test, re-running made it pass.

**Review by yusufkandemir — CHANGES_REQUESTED** [review]
Declaring and emitting kebab-case events is wrong, at least it used to be, even though listening to them is correct(_`@kebab-case`_). If you check the code base, you'll see that most stuff has been converted to camel case. This has probably been overlooked. So, the correct usage is `factoryFailed`, all other uses should be converted to this including the `emits` definition.

**Comment by amal-qb** [comment]
@yusufkandemir I have made the requested changes. Can you please review it again?

**Review by yusufkandemir — APPROVED** [review]

**Comment by yusufkandemir** [comment]
Thanks for contributing 👏 Will be available in the next release.

**Pull request merged**
