### PR TITLE
Recursive ignore of .DS_store and Thumbs.db

### PR DESCRIPTION
**Pull request by kasp1**
Recursive ignore of .DS_store and Thumbs.db

### CODE REVIEW

**Comment by kasp1** [comment]
Check this one before merging, looks like opinions are different https://stackoverflow.com/questions/18393498/gitignore-all-the-ds-store-files-in-every-folder-and-subfolder

**Comment by rstoenescu** [comment]
Hi, don't really have to look into it. The .gitignore additions seem fine to me. Do we need anything else?

**Comment by kasp1** [comment]
Should work like this

**Comment by dhax** [comment]
This was already working recursively before just fine and .DS_Store is the de facto standard entry in like every .gitignore file out there. Just saying...

**Comment by rstoenescu** [comment]
@kasp1 do we really need this change? I see that @dhax has a point and most repos on github simply specify `.DS_store` instead of `**/.DS_store` (same for `.Thumbs.db`). I don't own a Mac to test it out though.

**Comment by kasp1** [comment]
It looks like it doesn't matter whether it's `**/.DS_store` or `.DS_store`, so it can be just merged, because it adds `.Thumbs.db`.

**Comment by rstoenescu** [comment]
Ok, it's been already merged. Thanks for the confirmation.

**Pull request merged**
