### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by Iworb**
- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by rstoenescu** [comment]
Thank you!

**Comment by Iworb** [comment]
In the future I will check in more detailed way about 'update' and 'refresh' translations, because they have the same meaning in russian.

**Comment by olegvakulenko** [comment]
@Iworb 
Hi!
This PR has couple errors. Is my comment on code visible for you?

**Comment by olegvakulenko** [comment]
@Iworb 
And one more thing.
On buttons usually use _verb_ instead of _noun_. So as `close: 'Закрыть'` must be `cancel: 'Отменить'`,
Thanks.

**Pull request merged**
