### PR TITLE
[v1] vertical tabs

### PR DESCRIPTION
**Pull request by rob-64**
https://github.com/quasarframework/quasar/issues/2437

Decided to do this on V1 as I assume I'll be using it shortly :)

Tried to update the dev to show an example as well.

screen shot 2018-12-09 at 11 54 10 am

### CODE REVIEW

**Comment by rstoenescu** [comment]
Thank you for updating the PR. This will go into 1.0.

**Comment by rob-64** [comment]
Updated to latest changes in dev branch

**Comment by rstoenescu** [comment]
Hi @rob-64 

Thanks for keeping this up to date. I assure you this will go into v1. Sorry for the delay. Lots going on.

**Comment by rob-64** [comment]
@rstoenescu yea, no worries, I can see all the progress going on 👍 maybe I am blind, but how do I run the docs locally?

**Comment by rob-64** [comment]
Merged in latest dev branch

**Comment by rob-64** [comment]
Updated

**Comment by rstoenescu** [comment]
Sorry it took so long. Will be available in beta.11.
Many thanks for contributing with this cool feature!

**Comment by rob-64** [comment]
👍

**Comment by rstoenescu** [comment]
Added a nice example with vert tabs and QSplitter + QTabPanels.

vert-tabs

**Pull request merged**
