### PR TITLE
feat(docs) backlink in codepens

### PR DESCRIPTION
**Pull request by nothingismagick**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/dev/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by nothingismagick** [comment]
see here:
https://codepen.io/nothingismagick/pen/eoQBWp?&editable=true&editors=101

**Comment by nothingismagick** [comment]
@rstoenescu - any reason not to merge (other than 10,000 things on your plate of course)

**Comment by rstoenescu** [comment]
1. What's the reasoning behind this? aka "why do we need it".
2. Based on answer on point 1, would it make more sense to just add an html comment instead, like `<!-- Forked from LINK -->`. There's some codepens generated from docs that have footer or some drawer logic that would get hidden by this banner.

**Comment by nothingismagick** [comment]
1. Because the workflow when triaging 95% of the problems people have is:
 - go to their codepen
 - go to v1.quasar-framework.org
 - click in search and type appropriate search term
 - find (if you are lucky) the right one
 - compare with existing etc.
This is tedious and having a backlink would help out.
2. Having it as a comment would be ok too, but it doesn't have to be a footer bar. That was just the first pass at it.

**Comment by rstoenescu** [comment]
Go for the comment approach then.

**Pull request merged**
