### PR TITLE
feat(app-vite): Add pnpm package manager

### PR DESCRIPTION
**Pull request by keyding**
**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [x] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on an Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**

Support for `pnpm` package manager

### CODE REVIEW

**Comment by yusufkandemir** [comment]
Thanks for the contribution. We need to ensure pnpm works fine in every case before merging this. So, this **may** be merged only if everything goes fine with #13399.

**Comment by taai** [comment]
Update also this line!

```javascript
// replace this
warn('Please install Yarn or NPM before running this command.\n')
// with this
warn('Please install Yarn, NPM or PNPM before running this command.\n')
```

**Comment by keyding** [comment]
> Update also this line!
> 
> ```js
> // replace this
> warn('Please install Yarn or NPM before running this command.\n')
> // with this
> warn('Please install Yarn, NPM or PNPM before running this command.\n')
> ```

Done.

**Comment by yusufkandemir** [comment]
Closing in favor of an older PR #13106 which covers both app-vite and app-webpack.

**Pull request closed without merging**
