### PR TITLE
BackToTop component

### PR DESCRIPTION
**Pull request by fsgiudice**
Simple component to Scroll to Top of page

### CODE REVIEW

**Comment by murbanowicz** [comment]
Another contributor, great!
I just think that DEMO should go to documentation?

**Comment by rstoenescu** [comment]
Thanks for the PR! Will check it out by the end of the week and merge it.

**Comment by rstoenescu** [comment]
Hi,

First of all thank you for taking time to contribute!!!
I really hope you don't mind, but went with another approach: back to top as a directive.

**Comment by fsgiudice** [comment]
@rstoenescu 
Hi Razvan, well done. 
Continuing on forum...
Thank you

**Pull request closed without merging**
