### PR TITLE
fix(docs/api): public vs statics

### PR DESCRIPTION
**Pull request by hawkeye64**

### CODE REVIEW

**Comment by rstoenescu** [comment]
Ups, seems like Dan duplicated this and got to merge that first :(

**Comment by hawkeye64** [comment]
Yep, his was better anyway. He caught some things I missed.

**Comment by rstoenescu** [comment]
He only did the v1 PR. If he caught things, can you port those to the v2 docs pls?

**Comment by hawkeye64** [comment]
@rstoenescu Done: https://github.com/quasarframework/quasar/pull/11896

**Pull request closed without merging**
