### PR TITLE
feat(ui,table): Q-Table support to columns drag resizing #5115

### PR DESCRIPTION
**Pull request by codeorbit10**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x ] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [x ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

Adding a prop in order to be able to resize the columns of the table by dragging them.
Just add a resizable-columns prop in the q-table in order to test it.

### CODE REVIEW

**Comment by rstoenescu** [comment]
Hi,

Thank you for contributing and for your efforts on this Pr!
This PR's implementation however has a few issues, most notably the fact that it adds event listeners at mount point. But columns can change (add/remove), so it will not really work as intended. The approach seems like a jquery one rather than vue. The good way to go would be to use QTh component to handle resizing.

**Comment by greyufo** [comment]
doesnt' build, error in  QTh.json. missing defenitions

**Comment by rootux** [comment]
@rstoenescu Is there a plan to add this functionality to Quasar Table?

**Comment by rzfrsn** [comment]
This feature is really needed ..

**Comment by MilosPaunovic** [comment]
@rzfrsn Check this out:
https://github.com/quasarframework/quasar/issues/5115#issuecomment-734966793

**Comment by rzfrsn** [comment]
Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rzfrsn** [comment]
> @rzfrsn Check this out:
> https://github.com/quasarframework/quasar/issues/5115#issuecomment-734966793

Thanks @MilosPaunovic

**Comment by hope-zjl** [comment]
Hello, please tell me, when the table appears horizontal scroll bar, this column dragging function is disabled, how should I solve it?

**Pull request closed without merging**
