### PR TITLE
perf(utils/is): tweak in isDeepEqual

### PR DESCRIPTION
**Pull request by jesusvilla**
This allows to reduce times when executing isDeepEqual.
Look: https://jsbench.me/esk6thpf15/1

### CODE REVIEW

**Comment by jesusvilla** [comment]
Look: https://jsbench.me/esk6thpf15/2

Firefox:
image

Chrome:
image

**Comment by rstoenescu** [comment]
I'd like to see a jsperf.com between old variant and new one pls.

**Comment by jesusvilla** [comment]
Ok. https://jsperf.com/isdeepequal/1

image

image

**Comment by jesusvilla** [comment]
@rstoenescu sorry, the tests for jsperf were not well done, look again please:
https://jsperf.com/isdeepequal/2


| Test                               | chrome         | firefox        |
|------------------------------------|----------------|----------------|
| equal: Object (3 level)            | **3,232,975**  | 1,531,246      |
| isDeepEqual: Object (3 level)      | 1,797,989      | **1,580,692**  |
| equal: Collection                  | **2,536,470**  | **1,732,740**  |
| isDeepEqual: Collection            | 1,038,026      | 1,282,278      |
| equal: Array one-dimensional       | **13,142,088** | **11,082,772** |
| isDeepEqual: Array one-dimensional | 1,782,119      | 3,240,927      |

image

image

**Comment by rstoenescu** [comment]
I meant between the current isDeepEqual and the new one (yours).

**Comment by jesusvilla** [comment]
this is done, the current one is called "isDeepEqual" and the new one (mine) is called "equal"

**Comment by rstoenescu** [comment]
Ah, I see now. Beautiful work!! Wanna see more of this <3

**Pull request merged**
