### PR TITLE
feat: Allow custom value for QSelect and QDialogSelect

### PR DESCRIPTION
**Pull request by pdanpdan**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [X] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [X] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/master/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [X] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

For select components sometimes one needs to provide a shorter or different custom value.
Like the number of selected items in case of a lot of options selected.

Unified the actualValue code in QSelect and QDialogSelect. Maybe it should be extracted in select-mixin.

### CODE REVIEW

**Comment by rstoenescu** [comment]
Hi, let's find a better name for this prop and merge the PR. "custom-value" is a little bit confusing. Anyone got any ideas?

**Comment by smolinari** [comment]
Wouldn't this be something userland could do on their own with a computed property?

Scott

**Comment by pdanpdan** [comment]
It can be computed in userland, this is just the glue to allow it to be displayed. The name was a derivate of actualValue. Maybe the old staticLabel is better?

**Comment by rstoenescu** [comment]
@pdanpdan Good 'ol `staticLabel` is not good too. It confuses the developer as its name makes you think it interferes with `float-label` or `stack-label`, which is not the case. How about naming it `template`? Does it sound good to you? I'm open to more suggestions.

**Comment by smolinari** [comment]
value-converter or conversion
alt-value or alternative-value
value-mutation

??? 😄 

Scott

**Comment by rstoenescu** [comment]
`display-value` ?

**Comment by smolinari** [comment]
Sounds good to me!

Scott

**Comment by rstoenescu** [comment]
@pdanpdan does `display-value` sound good to you too?

**Comment by pdanpdan** [comment]
Yes, it sounds good.

**Comment by rstoenescu** [comment]
Ok, then let's do it like this.

**Pull request merged**
