### PR TITLE
Full material specs for input controls

### LINKED ISSUE #1631: Extra padding-bottom in QInput when inside QField
### Software version

OS: Darwin(17.4.0) - darwin/x64
Browser: Google Chrome Version 64.0.3282.167 (Official Build) (64-bit)

Global packages                 
  NodeJs                     8.9.4
  NPM                           5.6.0
  yarn                          Not available
  quasar-cli                    0.15.1
  vue-cli                       2.9.3
  cordova                       7.0.1

Important local packages        
  quasar-cli                    0.15.1
  quasar-framework              0.15.1
  quasar-extras                 1.0.2
  vue                           2.5.13
  vue-router                    3.0.1
  vuex                          3.0.1
  electron                      Not available
  babel-core                    6.26.0
  webpack                       3.11.0  

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/waugrryy/197/

### What did you get as the error?
No error. It is UI related.

### What were you expecting?
The same spacing for padding-bottom as when QInput is used without the QField.

### What steps did you take, to get the error?
Copy&Pasted the example: http://quasar-framework.org/components/input-textfield.html#Basic-Usage-with-QField

### Research Notes:
There were some changes in the code that could be related to this: https://github.com/quasarframework/quasar/commit/c77f7ab83fbdff635bef1c7733c65128bb0374c3#diff-b8a34ea846af1d8b759d63c8d92bd37b

Mo provided a link to the guidelines: https://material.io/guidelines/components/text-fields.html# Guidelines say it should be 8px. In 0.15  there are 10px. The text is 2px to high

Screenshot:
q-field-q-input

### LINKED ISSUE #1776: [15.7] QTable "Rows per page" dropdown label spacing in IE11 issue
Problem can be seen on play app at:
http://quasar-framework.org/quasar-play/android/index.html#/showcase/grouping/table/table-features

In IE11, if you select any 2 digit "Rows per page" the number positions itself over the dropdown icon.

capture

Looks fine in Chrome

Thanks!

### LINKED ISSUE #1812: q-input line changes and flickers when resizing window @ MS Edge @ Win 10
when resizing window the width of the input field lines varies:

image

### LINKED ISSUE #2003: QSelect does not show placeholder text when using "chips".
### Software version

Operating System                Linux(4.4.0-1054-aws) - linux/x64
NodeJs                          8.11.1

Global packages
  NPM                           5.8.0
  yarn                          Not available
  quasar-cli                    0.15.14
  vue-cli                       2.9.3
  cordova                       8.0.0

Important local packages
  quasar-cli                    0.15.14 (Quasar Framework CLI)
  quasar-framework              0.15.10 (Build responsive websites, PWAs, hybrid mobile apps and Electron apps, all simultaneously using same codebase)
  quasar-extras                 1.0.2   (Quasar Framework fonts, icons and i18n.)
  vue                           2.5.16  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                    3.0.1   (Official router for Vue.js 2)
  vuex                          3.0.1   (state management for Vue.js)
  electron                      Not available
  babel-core                    6.26.0  (Babel compiler core.)
  webpack                       3.11.0  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server            2.11.1  (Serves a webpack app. Updates the browser on changes.)

### What did you get as the error?

QSelect does not show placeholder text when using "chips".

### What were you expecting?

QSelect to show placeholder text when using "chips".

### What steps did you take, to get the error?

Simply add a QSelect with some text in placeholder and enable chips, placeholder will always be empty.

### LINKED ISSUE #2084: [Bug] QInput letters are cut off bottom: line-height fix needed
On Safari and Chrome on 0 zoom in writing 'g's inside a q-input make them cut off on the bottom.

image

The root of the problem seems to be that the `height` of q-input is set, but the `line-height` isn't.
Setting the line height fixes the problem.

I have created a pen with a fix button so you can compare it and see the fix:
https://codepen.io/mesqueeb/pen/XqGMMd

### LINKED ISSUE #2114: table / slot top-right / different behaviour on chrome and edge
`<template slot="top-right" slot-scope="props">
        <q-search
          hide-underline
          v-model="filter"
          placeholder="xxx"
          clearable
        >
        </q-search>
      </template>`

as part of my table.

On Chrome:

image

On Edge, Win 10:

image

### LINKED ISSUE #2236: QInput textarea has extra height in bottom
QInput textarea has extra height in bottom, and if label is used content is closer to the label, compared to normal QInput. I'm using quasar 0.16, and vue 2.5.16.

### PR DESCRIPTION
**Pull request by pdanpdan**
Refactor controls styles to match the new material design

Added props:
- outline
- box
- full-width
- dense for all types

close #1631, close #1776, close #2003, close #2114, close #2084, close #1812, close #2236

### CODE REVIEW

**Comment by jean-moldovan** [comment]
cool, no breaking changes expected?

**Comment by pdanpdan** [comment]
In the newest version no, none (or none that I can think of)

**Comment by murbanowicz** [comment]
Is it going to be merged soon?

**Comment by murbanowicz** [comment]
@pdanpdan  - why it got closed, not merged?

**Comment by rstoenescu** [comment]
@murbanowicz This will go into v1.0 (next version).

**Pull request closed without merging**
