### PR TITLE
fix(ui): QIcon interpretation of 'M.' as 'material-icons' is incorrect

### PR DESCRIPTION
**Pull request by hawkeye64**

### CODE REVIEW

**Comment by hawkeye64** [comment]
Fix is also added into v1: https://github.com/quasarframework/quasar/pull/11583

**Comment by rstoenescu** [comment]
Rewritten to more appropriate: `/^[Mm]\s?[-+]?\.?\d/`

**Comment by hawkeye64** [comment]
I was adding that at the same time :)

**Comment by rstoenescu** [comment]
On the Qv1 PR. There's one from Dan as well, backporting more stuff from Qv2 along the way.
One comment on the Qv1 PR -> rather than the greedy `\s*` I'd rather prefer the more performant match of "one space or nothing" `\s?`.

Is it ok for you that I merge Dan's PR? (cause it has more stuff to it) Otherwise please talk to each other and tell me how you want it, because I can't push both PRs without merge errors :)

**Comment by hawkeye64** [comment]
Yes, merge Dan's PR, np

**Comment by hawkeye64** [comment]
https://github.com/hawkeye64/quasar-extras-svg-icons/issues/18

**Pull request merged**
