### PR TITLE
feat(a11y/QMenu/QDialog/QTabs): Add KeyGroupNavigation directive; Wrap arround keyboard navigation; fix RTL mode; improve tabs scrolling #6562, #6560, #8140, #5266, #4068, #6736, #8358, #8578

### PR DESCRIPTION
**Pull request by pdanpdan**
https://pdanpdan.github.io/quasar-docs/vue-directives/key-group-navigation

- fix RTL mode
- improve tabs scrolling
- allow unique TAB target point in a group
- allow key navigation in group
- improve initial focusing on QMenu and QDialog
- tab goes from the end of the menu/dialog to the start
- shift+tab goes from the start of the menu/dialog to the end
- key navigation in tabs

TODO later: implement aria-activedescendant

#6562, #6560, #8140, #5266, #4068, #6736, #8358,  #8578

### CODE REVIEW

**Comment by pdanpdan** [comment]
Examples:

https://codepen.io/pdanpdan/pen/qBbdjNj
https://codepen.io/pdanpdan/pen/wvMaeWN
https://codepen.io/pdanpdan/pen/QWybgEX
https://codepen.io/pdanpdan/pen/ZEQGypb

**Comment by rstoenescu** [comment]
Top notch stuff! Will go into v1.13.0.

**Comment by Cmacu** [comment]
this looks like a great feature

**Comment by cmcleese** [comment]
Will this directive make into Quasar v2 as well?

**Pull request closed without merging**
