### PR TITLE
feat: add typescript definitions

### PR DESCRIPTION
**Pull request by d3v2a**
i think it's not perfect (i start using typescrypt one week ago) but it's a good starting point.

  Utils, LocalStorage, SessionStorage is not done due lack of time ...

### CODE REVIEW

**Comment by icfr** [comment]
typescrypt definition finished fully tested in vsc

**Comment by igorgo** [comment]
I think that it is not necessary here.
There is a special project for such definitions - https://github.com/DefinitelyTyped/DefinitelyTyped.

**Comment by John0x** [comment]
@igorgo it would benefit everyone if it was included in the main repo. The @types (formerly DefinitelyTyped) are for third party typings

**Comment by nothingismagick** [comment]
@outofmemoryagain and @rstoenescu - is this still helpful or can it be closed because the work being done on the typedefs in core and this app-extension here:

https://github.com/quasarframework/app-extension-typescript

**Pull request closed without merging**
