### PR TITLE
Fixes tab scroll animation and drawer slide left animation.

### PR DESCRIPTION
**Pull request by codingfriend1**
Makes tab and left drawer slide animations smoother on low end devices for a more native feel. 

The scroll behavior of the tabs was causing repaints every 5 ms and was looking jittery. This replaces that with native element.scrollTo() for native scroll performance.

The left drawer would start loading a route before it was fully shut causing the animation to pause half way. By increasing the delay to 370ms from drawer close to loading the route, the animation has time to finish and appears smoother.

Also delays the closing of the drawer if the keyboard is currently open, to prevent an animation glitch and give the keyboard time to close. Tested in cordova android, not ios.

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] It's been tested with all Quasar themes
- [x] It's been tested on a Cordova (iOS, Android) app
- [x] It's been tested on a Electron app
- [x] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/master/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rstoenescu** [comment]
I see a few problems with this:

1. On mobile you can switch back and forth from portrait to landscape and this will trigger the isKeyboardShown part.
2. There is no element.scrollTo() ??? Or am I missing something?

**Comment by codingfriend1** [comment]
I have orientation working on mobile. scrollTo is a native method added onto all elements.

**Comment by rstoenescu** [comment]
1. When you change mobile orientation this will fail. Am I missing something?
2. Can you point to the web specs link regarding scrollTo on an Element pls?

**Comment by codingfriend1** [comment]
This commit should fix the mobile orientation

https://github.com/quasarframework/quasar/pull/999/commits/21728503f5bb1e0bcd2b025ce73e3216c9d5b9c6

scrollTo:
https://www.w3schools.com/jsref/met_win_scrollto.asp
https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo

I can confirm this is working for elements besides window in chrome, firefox, and safari. Although safari doesn't seem to be smooth. If you inspect any element you will notice it has this property. And if you remove the original animation this will still work.

**Comment by rstoenescu** [comment]
@codingfriend1 

Ok, please note that it is "window.scrollTo()" and NOT a "DomElement.scrollTo"
Also, for the isKeyboardOpened, what if the user opens up the website/app in landscape orientation?

Please push any changes to this PR too, don't pile up PRs.

**Comment by codingfriend1** [comment]
I have thoroughly tested the device orientation changes and made a few changes. It should detect keyboard being open or closed accurately even if the user rotates the screen, during/not-during the keyboard being open.

The scrollTo will work for elements, at least in modern browsers, I haven't tested older browsers.

**Pull request closed without merging**
