### PR TITLE
Form validation page

### PR DESCRIPTION
**Pull request by panstromek**
Just a blind copypaste for start

### CODE REVIEW

**Comment by rstoenescu** [comment]
Hi,

In this particular case, it's about http://0.0.0.0:8080/form/input-validate (`yarn dev` in /quasar folder).
Everything's obsolete here.

**Comment by panstromek** [comment]
I have seen that page but I thought using `:rules` is just another option. From my understanding the code here is still usable in new Quasar.. do you imply that Vuelidate support has been dropped?

**Comment by rstoenescu** [comment]
No, it can still be used. But it probably deserves another page in docs.

**Comment by rstoenescu** [comment]
For now just focus on the internal `rules` prop as indicated.

**Comment by panstromek** [comment]
I see.. well. This will take me a bit more time then.

**Comment by rstoenescu** [comment]
No problem. Thanks for contributing! If you wanna choose something else it's ok too, just throwing that out.

**Pull request closed without merging**
