### PR TITLE
feat(date utils): add UTC support for startOfDate/endOfDate #8052

### PR DESCRIPTION
**Pull request by pdanpdan**

### CODE REVIEW

**Comment by icksky** [comment]
why `utc` is not a optional params like function `adjustDate`?

**Comment by pdanpdan** [comment]
@icksky what do you mean?

**Comment by icksky** [comment]
eslint alert the error `TS2554: Expected 3 arguments, but got 2.` after I update to this.
I think the functions types should be
```
function startOfDate(date: Date | number | string, option: DateUnitOptions, utc?: boolean): Date;
function endOfDate(date: Date | number | string, option: DateUnitOptions, utc?: boolean): Date;
```
like the type of `adjustDate`
```
function adjustDate(date: Date | number | string, options: ModifyDateOptions, utc?: boolean): Date;
```

change `utc: boolean` to `utc?: boolean`

**Comment by pdanpdan** [comment]
Ah, ok, please make a PR to fix it. I missed it.

**Pull request merged**
