### PR TITLE
Just for ref - feat(Platform): Improve detection of ios when emulated or used with request desktop site

### PR DESCRIPTION
**Pull request by pdanpdan**
ref #5430

### CODE REVIEW

**Comment by ibrainventures** [comment]
hi @pdanpdan , hi @rstoenescu 
i am working with this commit since some days, and the ipados / render as desktop with those additions are acknowledge. May this will go into the master?

**Comment by rstoenescu** [comment]
@ibrainventures chose a different path, but it has the same effect. you'll be happy when you upgrade to v1.7.4 :)

**Comment by ibrainventures** [comment]
hi @pdanpdan  hi @rstoenescu 
i saw today the new , modified version and tested on quasar.dev all features. ! Thanks for all yourwork.
I thought - and hoped - that the qmenu etc. deposition with zoomed / viewport on ios 13+ / ipados - requested as desktop - with this differentiation works .. but it will not work ..

have you got a idea, why this viewport regulation / qmenu positioning - which is according to the sourcecode respected - not working on request as desktop ipados 13 ?

i tested the platform detection on quasar.dev and all vars are showing ios , webkit, ipad - with the request as desktop mode ...

**Comment by ibrainventures** [comment]
may quasar.dev is not completly updated ? .. i have no debug-ios-ipad option actually, so i cant view into the dom about those two vp css root vars ...

**Comment by pdanpdan** [comment]
We just tested, the QMenu/QTooltip is positioned correctly when zoomed.
Can you explain in more details what seems to be wrong?

**Comment by ibrainventures** [comment]
hi @pdanpdan 
ipad ios 13 , request as desktop, qmenu , tooltip, etc. are depositioned - if a little zoomed.

the plattform detection helps maybe - there are some little differences. 
ipad-not-as-dekstop
ipad-as-desktop
depos1
depos2

**Comment by ibrainventures** [comment]
platform detection : some differences in the ranking  - (position of the characteristic)

**Comment by ibrainventures** [comment]
same ipad , same minute, same webside (quasar.dev)

**Comment by pdanpdan** [comment]
We'll check, thanks for reporting.

**Comment by ibrainventures** [comment]
but the icons looks great !! and all other things .. sorry for beeing sometimes the party-crasher ...

**Comment by rstoenescu** [comment]
Not at all! Please do comment. It’s helping Quasar become insanely good ;)

**Comment by ibrainventures** [comment]
good morning @pdanpdan @rstoenescu 

some good and some bad news

i freshly gitcloned the quasar git and started locally a quasar dev inside the doc dir .. there the viewport adaption works fine, and qtooltip and qmenu are on the right place with a zoomed request as desktop.

i updated our webapp with a heavy patched 1.7.4 and there the viewport adaption also works fine.

Now the bad news:

But still on quasar.dev a non good working 1.7.4 .. So i think your quasar.dev deploy is half-failured or some cdn s or too long cache-times for .js are interferring the site actually.

May a complete cleanup on the webspace and a fresh deploy can  solve this "issue" ...

Some pics from the local running /docs :

good1


good2

**Comment by rstoenescu** [comment]
@ibrainventures  Found the culprit. You're safe with the mobile apps. It's only a SSR issue (which I fixed in next v1.7.5 - to be released).

**Comment by ibrainventures** [comment]
@rstoenescu perfect !! have a nice weekend.

**Comment by rstoenescu** [comment]
u too!

**Comment by ibrainventures** [comment]
only for completness

the 1.8.3 deployed quasar.dev is working fine with the viewport zoom. 
All menu dropdowns are on the right place.

**Pull request closed without merging**
