### PR TITLE
access file when file uploaded

### PR DESCRIPTION
**Pull request by ceau**
I need to access the file   when uploaded. when assign the name, I can't access the file outside the uploader component

### CODE REVIEW

**Comment by mstaack** [comment]
how about other cases like: **https://github.com/quasarframework/quasar/pull/535/commits/28eed8c4f36986482c64bb27f83f76d68b603a66#diff-683217980df7463f98151a63c673c7efL237**

**Comment by rstoenescu** [comment]
@mstaack good catch.
Added those changes too and merged.

**Comment by rstoenescu** [comment]
Also improved the other events too. Pushed commit. Available in future v0.14.

| Event | Description |
| --- | --- |
| `@add(files)` | Triggered when file is picked for upload |
| `@remove(file)` | Triggered when file is removed from upload queue |
| `@upload(file, xhr)` | Triggered individually for each file that has just been uploaded |
| `@fail(file, xhr)` | Triggered individually for each file that has encountered error while uploading |
| `@start` | Triggered when upload has started |
| `@finish` | Triggered when upload of file(s) has ended (with success or failure) |

**Comment by ceau** [comment]
nice

**Pull request merged**
