### PR TITLE
fix(ui): q-item within QMenu should be selectable using the space key (fix: #16107)

### LINKED ISSUE #16107: The q-item within QMenu cannot be selected using the space key.
### What happened?

The q-item within QMenu cannot be selected using the space key. However, selection is possible using the enter key.

### What did you expect to happen?

When the space key is pressed, it should select the item in the same way as the enter key does.

### Reproduction URL

https://codepen.io/Hiroshiba/pen/BaGPwqe

### How to reproduce?

1. Click on the menu.
2. Repeatedly press the tab key to focus on any item.
3. Press the space key.

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amal-qb**
**What kind of change does this PR introduce?** 

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch (or `v[X]` branch)
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] It's been tested on a Cordova (iOS, Android) app
- [x] It's been tested on an Electron app
- [x] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/quasarframework/quasar/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**

Fixes #16107

### CODE REVIEW

**Comment by amal-qb** [comment]
@yusufkandemir Could you please check why the UI tests are failing with below error:

> error @quasar/app-vite@2.0.0-alpha.34: The engine "node" is incompatible with this module. Expected version "^30 || ^28 || ^26 || ^24 || ^22 || ^20 || ^18". Got "16.20.2"

**Comment by yusufkandemir** [comment]
@amal-qb the issue is clear, the workflows are using Node 16 which is not supported in app-vite v2 beta. I have fixed it: https://github.com/quasarframework/quasar/commit/7a7444a241cf8786c623d59e099f4bf41de66557
You need to rebase your PR to get it to run using the updated workflow.

**Comment by amal-qb** [comment]
@yusufkandemir Thanks! But now I'm getting an error for the "UI Tests Results" check:

> Error processing result file

image

**Comment by yusufkandemir** [comment]
@amal-qb it's been like that for a while, you can ignore it for now. I will investigate it another time.

**Comment by rstoenescu** [comment]
Thanks for contributing!

**Pull request merged**
