### PR TITLE
feat(QDate): add day slot for content #7076, #7290

### PR DESCRIPTION
**Pull request by pdanpdan**
https://pdanpdan.github.io/quasar-docs/vue-components/date#Day-scoped-slot

### CODE REVIEW

**Comment by webnoob** [comment]
I don't see this new slot in the QDate API in the docs. Did you just forget to add it or do it on purpose?

**Comment by pdanpdan** [comment]
It's the green part in the .json - it's a scoped slot.

**Comment by webnoob** [comment]
Shouldn't it be appearing in this then?
image

**Comment by pdanpdan** [comment]
https://pdanpdan.github.io/quasar-docs/vue-components/date#QDate-API
Did you copy the ui build in node_modules/quasar/...?

**Comment by webnoob** [comment]
All good, I needed to build then copy paste into node_modules in docs.

**Pull request merged**
