### PR TITLE
feat(mini-to-overlay): allow mini drawer to "open" as overlay

### PR DESCRIPTION
**Pull request by smakinson**
A new property mini-to-overlay is added to allow letting the QDrawer be mini and move to full size without moving the page content, as an overlay. The drawer can still be hidden via v-model.

The reason behind this feature is I was trying to toggle overlay in combination with turning mini off for the QDrawer and it lead to trying to override css with !important and I thought it might be something others would like as well.

This adds a new property `mini-to-overlay` to QDrawer to allow it to move from mini=true to mini=false without moving the page content and overlay the page. The drawer can still be hidden via v-model and I didn't touch the behavior or breakpoint props. It should not be used in combination with overlay.

I also added new toggles to test it in the dev layout page and fixed the selects for the behavior. Set Left Mini to Overlay on and then toggle the mini property.

What do you think? Did I miss anything? Do I need to update docs somewhere?

### CODE REVIEW

**Comment by smakinson** [comment]
Relates to this feature request: https://github.com/quasarframework/quasar/issues/3945

**Comment by rstoenescu** [comment]
Excellent idea! Thank you for your time.
I'll try my best to add this to the final 1.0.0 build. There's a few minor bugs that need to be squashed.

**Comment by rstoenescu** [comment]
Fixed:
* Setting v-model to "false" does not free up layout space
* Force drawer into fixed position otherwise it breaks header/footer if view is along the lines of `hHh lpr fFf`.

Thank you for contributing!

**Comment by miladmeidanshahi** [comment]
Nice feature, @rstoenescu When do you want to release?

**Comment by miladmeidanshahi** [comment]
The overlay prop on drawer doesn't work, Is this PR fix this issue?

**Comment by rstoenescu** [comment]
@miladmeidanshahi `overlay` prop is one thing, and `mini-to-overlay` another

**Pull request merged**
