### PR TITLE
feat(ui) add "outlined" prop to QBadge

### PR DESCRIPTION
**Pull request by lucasfernog**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [x] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

2019-11-19_183x145_screenshot

2019-11-19_177x143_screenshot

### CODE REVIEW

**Comment by rstoenescu** [comment]
Nice idea and good work.

Some thoughts (went into a commit after merging):
* Never use a default value for a color prop. Makes CSS overriding near impossible.
* For consistency purposes, it should be "outline".

**Comment by lucasfernog** [comment]
I thought the standard was "outlined" like QField :(

Thx for the tips, I'm an UI noob lol

**Comment by rstoenescu** [comment]
There are still a few "outlined" out there, but that was a mistake and we cannot introduce breaking changes now. But more important, it must definitely match its "sister" component QChip.

Don't sweat it, looking forward to more PRs, regardless if for UI or CLI <3

**Comment by lucasfernog** [comment]
Good to know, thanks!

**Pull request merged**
