### PR TITLE
feat(QUploader): new scopedSlot 'error-icon'

### PR DESCRIPTION
**Pull request by hawkeye64**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [X] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [X] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

This has been asked for by several users in the past. Recently a new one today.

**Other information:**
image

### CODE REVIEW

**Comment by hawkeye64** [comment]
This is what the default one looks like:
image

**Comment by lucasfernog** [comment]
Nice uploaded PDF example, Jeff!

**Comment by hawkeye64** [comment]
@lucasfernog I was wondering if anyone would catch that :) Figured @nothingismagick would for sure. He's likely be too busy to be trolling issues.

**Comment by lucasfernog** [comment]
Yeah he is working on something cooool

**Comment by hawkeye64** [comment]
Use this example to add icon: https://quasar.dev/vue-components/uploader#Example--Custom-files-list

**Pull request closed without merging**
